import bcrypt from 'bcryptjs';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ---------------------------------------------------------------------------
// Translation keys — ~400 keys × 3 locales
// Run with: node prisma/seed.js  (idempotent — skipDuplicates keeps admin edits)
// ---------------------------------------------------------------------------
const KEYS = [
  // common
  { key:'common.loading',         de:'Laden…',             en:'Loading…',           fr:'Chargement…' },
  { key:'common.saving',          de:'Speichern…',         en:'Saving…',            fr:'Enregistrement…' },
  { key:'common.save',            de:'Speichern',          en:'Save',               fr:'Enregistrer' },
  { key:'common.cancel',          de:'Abbrechen',          en:'Cancel',             fr:'Annuler' },
  { key:'common.delete',          de:'Löschen',            en:'Delete',             fr:'Supprimer' },
  { key:'common.edit',            de:'Bearbeiten',         en:'Edit',               fr:'Modifier' },
  { key:'common.close',           de:'Schließen',          en:'Close',              fr:'Fermer' },
  { key:'common.confirm',         de:'Bestätigen',         en:'Confirm',            fr:'Confirmer' },
  { key:'common.search',          de:'Suchen',             en:'Search',             fr:'Rechercher' },
  { key:'common.filter',          de:'Filtern',            en:'Filter',             fr:'Filtrer' },
  { key:'common.all',             de:'Alle',               en:'All',                fr:'Tous' },
  { key:'common.yes',             de:'Ja',                 en:'Yes',                fr:'Oui' },
  { key:'common.no',              de:'Nein',               en:'No',                 fr:'Non' },
  { key:'common.error',           de:'Fehler',             en:'Error',              fr:'Erreur' },
  { key:'common.success',         de:'Erfolgreich',        en:'Success',            fr:'Succès' },
  { key:'common.optional',        de:'Optional',           en:'Optional',           fr:'Facultatif' },
  { key:'common.required',        de:'Pflichtfeld',        en:'Required',           fr:'Obligatoire' },
  { key:'common.back',            de:'Zurück',             en:'Back',               fr:'Retour' },
  { key:'common.next',            de:'Weiter',             en:'Next',               fr:'Suivant' },
  { key:'common.submit',          de:'Absenden',           en:'Submit',             fr:'Envoyer' },
  { key:'common.reset',           de:'Zurücksetzen',       en:'Reset',              fr:'Réinitialiser' },
  { key:'common.add',             de:'Hinzufügen',         en:'Add',                fr:'Ajouter' },
  { key:'common.remove',          de:'Entfernen',          en:'Remove',             fr:'Supprimer' },
  { key:'common.show',            de:'Anzeigen',           en:'Show',               fr:'Afficher' },
  { key:'common.hide',            de:'Ausblenden',         en:'Hide',               fr:'Masquer' },
  { key:'common.unknown',         de:'Unbekannt',          en:'Unknown',            fr:'Inconnu' },
  { key:'common.private',         de:'Privat',             en:'Private',            fr:'Privé' },
  { key:'common.public',          de:'Öffentlich',         en:'Public',             fr:'Public' },
  { key:'common.friends',         de:'Freunde',            en:'Friends',            fr:'Amis' },
  { key:'common.kg',              de:'kg',                 en:'kg',                 fr:'kg' },
  { key:'common.cm',              de:'cm',                 en:'cm',                 fr:'cm' },
  { key:'common.date',            de:'Datum',              en:'Date',               fr:'Date' },
  { key:'common.time',            de:'Uhrzeit',            en:'Time',               fr:'Heure' },
  { key:'common.location',        de:'Ort',                en:'Location',           fr:'Lieu' },
  { key:'common.notes',           de:'Notizen',            en:'Notes',              fr:'Notes' },
  { key:'common.description',     de:'Beschreibung',       en:'Description',        fr:'Description' },
  { key:'common.photo',           de:'Foto',               en:'Photo',              fr:'Photo' },
  { key:'common.no_data',         de:'Keine Daten vorhanden.', en:'No data available.', fr:'Aucune donnée disponible.' },

  // nav
  { key:'nav.dashboard',    de:'Dashboard',       en:'Dashboard',        fr:'Tableau de bord' },
  { key:'nav.catches',      de:'Fangbuch',        en:'Catch Log',        fr:'Journal de pêche' },
  { key:'nav.spots',        de:'Angelspots',      en:'Fishing Spots',    fr:'Spots de pêche' },
  { key:'nav.forecast',     de:'Bissindex',       en:'Bite Index',       fr:'Indice de morsure' },
  { key:'nav.community',    de:'Community',       en:'Community',        fr:'Communauté' },
  { key:'nav.profile',      de:'Profil',          en:'Profile',          fr:'Profil' },
  { key:'nav.admin',        de:'Admin',           en:'Admin',            fr:'Admin' },
  { key:'nav.license',      de:'Angelschein',     en:'Fishing License',  fr:'Permis de pêche' },
  { key:'nav.logout',       de:'Abmelden',        en:'Log out',          fr:'Se déconnecter' },
  { key:'nav.login',        de:'Anmelden',        en:'Log in',           fr:'Se connecter' },
  { key:'nav.guidelines',   de:'Verhaltensregeln',en:'Guidelines',       fr:'Règles de conduite' },
  { key:'nav.impressum',    de:'Impressum',       en:'Legal Notice',     fr:'Mentions légales' },
  { key:'nav.privacy',      de:'Datenschutz',     en:'Privacy Policy',   fr:'Politique de confidentialité' },

  // footer
  { key:'footer.tagline',   de:'Dein digitales Angel-Tagebuch', en:'Your digital fishing diary', fr:'Votre journal de pêche numérique' },
  { key:'footer.links',     de:'Links',           en:'Links',            fr:'Liens' },
  { key:'footer.legal',     de:'Rechtliches',     en:'Legal',            fr:'Mentions légales' },
  { key:'footer.copyright', de:'© 2026 AngelMate. Alle Rechte vorbehalten.', en:'© 2026 AngelMate. All rights reserved.', fr:'© 2026 AngelMate. Tous droits réservés.' },

  // skill levels
  { key:'skill.beginner',      de:'Anfänger',         en:'Beginner',         fr:'Débutant' },
  { key:'skill.intermediate',  de:'Fortgeschritten',  en:'Intermediate',     fr:'Intermédiaire' },
  { key:'skill.expert',        de:'Profi',            en:'Expert',           fr:'Expert' },

  // auth
  { key:'auth.login_title',        de:'Willkommen zurück!',      en:'Welcome back!',           fr:'Bon retour !' },
  { key:'auth.login_sub',          de:'Melde dich an, um fortzufahren.', en:'Sign in to continue.', fr:'Connectez-vous pour continuer.' },
  { key:'auth.register_title',     de:'Konto erstellen',          en:'Create account',          fr:'Créer un compte' },
  { key:'auth.register_sub',       de:'Werde Teil der Community.', en:'Join the community.',    fr:'Rejoignez la communauté.' },
  { key:'auth.email',              de:'E-Mail',                    en:'Email',                   fr:'E-mail' },
  { key:'auth.password',           de:'Passwort',                  en:'Password',                fr:'Mot de passe' },
  { key:'auth.name',               de:'Name',                      en:'Name',                    fr:'Nom' },
  { key:'auth.region',             de:'Heimatgewässer / Region',   en:'Home waters / Region',   fr:'Eaux d\'origine / Région' },
  { key:'auth.skill_label',        de:'Erfahrungsstufe',           en:'Skill level',             fr:'Niveau d\'expérience' },
  { key:'auth.language_label',     de:'Sprache',                   en:'Language',                fr:'Langue' },
  { key:'auth.login_btn',          de:'Anmelden',                  en:'Sign in',                 fr:'Se connecter' },
  { key:'auth.register_btn',       de:'Registrieren',              en:'Register',                fr:'S\'inscrire' },
  { key:'auth.switch_to_register', de:'Noch kein Konto? Registrieren', en:'No account? Register', fr:'Pas de compte ? S\'inscrire' },
  { key:'auth.switch_to_login',    de:'Bereits registriert? Anmelden', en:'Already registered? Sign in', fr:'Déjà inscrit ? Se connecter' },
  { key:'auth.forgot_password',    de:'Passwort vergessen?',        en:'Forgot password?',        fr:'Mot de passe oublié ?' },
  { key:'auth.forgot_title',       de:'Passwort zurücksetzen',      en:'Reset password',          fr:'Réinitialiser le mot de passe' },
  { key:'auth.forgot_sub',         de:'Gib deine E-Mail-Adresse ein. Du erhältst einen Link zum Zurücksetzen.', en:'Enter your email address. You will receive a reset link.', fr:'Saisissez votre adresse e-mail. Vous recevrez un lien de réinitialisation.' },
  { key:'auth.forgot_btn',         de:'Link anfordern',             en:'Request link',            fr:'Demander le lien' },
  { key:'auth.forgot_loading',     de:'Sende…',                     en:'Sending…',                fr:'Envoi…' },
  { key:'auth.forgot_sent_title',  de:'E-Mail gesendet!',           en:'Email sent!',             fr:'E-mail envoyé !' },
  { key:'auth.forgot_sent_body',   de:'Falls ein Konto mit dieser Adresse existiert, erhältst du in Kürze einen Reset-Link.', en:'If an account exists for this address, you will receive a reset link shortly.', fr:'Si un compte existe pour cette adresse, vous recevrez un lien de réinitialisation sous peu.' },
  { key:'auth.forgot_back',        de:'Zurück zur Anmeldung',       en:'Back to sign in',         fr:'Retour à la connexion' },
  { key:'auth.reset_title',        de:'Neues Passwort festlegen',   en:'Set new password',        fr:'Définir un nouveau mot de passe' },
  { key:'auth.reset_new_pw',       de:'Neues Passwort',             en:'New password',            fr:'Nouveau mot de passe' },
  { key:'auth.reset_confirm_pw',   de:'Passwort bestätigen',        en:'Confirm password',        fr:'Confirmer le mot de passe' },
  { key:'auth.reset_pw_ph',        de:'Mindestens 8 Zeichen',       en:'At least 8 characters',  fr:'Au moins 8 caractères' },
  { key:'auth.reset_confirm_ph',   de:'Passwort wiederholen',       en:'Repeat password',         fr:'Répéter le mot de passe' },
  { key:'auth.reset_btn',          de:'Passwort speichern',         en:'Save password',           fr:'Enregistrer le mot de passe' },
  { key:'auth.reset_loading',      de:'Speichere…',                 en:'Saving…',                 fr:'Enregistrement…' },
  { key:'auth.reset_done_title',   de:'Passwort geändert!',         en:'Password changed!',       fr:'Mot de passe modifié !' },
  { key:'auth.reset_done_body',    de:'Du kannst dich jetzt mit deinem neuen Passwort anmelden.', en:'You can now sign in with your new password.', fr:'Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.' },
  { key:'auth.reset_go_login',     de:'Zur Anmeldung',              en:'Go to sign in',           fr:'Aller à la connexion' },
  { key:'auth.reset_err_mismatch', de:'Die Passwörter stimmen nicht überein.', en:'Passwords do not match.', fr:'Les mots de passe ne correspondent pas.' },
  { key:'auth.reset_err_short',    de:'Das Passwort muss mindestens 8 Zeichen lang sein.', en:'Password must be at least 8 characters.', fr:'Le mot de passe doit contenir au moins 8 caractères.' },
  { key:'auth.reset_err_no_token', de:'Ungültiger oder fehlender Reset-Token.', en:'Invalid or missing reset token.', fr:'Jeton de réinitialisation invalide ou manquant.' },
  { key:'auth.pw_placeholder',     de:'Passwort eingeben',          en:'Enter password',          fr:'Entrer le mot de passe' },

  // dashboard
  { key:'dashboard.greeting',         de:'Hallo, {{name}}! 👋',      en:'Hello, {{name}}! 👋',      fr:'Bonjour, {{name}} ! 👋' },
  { key:'dashboard.subtitle',         de:'Bereit für den nächsten Fang?', en:'Ready for the next catch?', fr:'Prêt pour la prochaine prise ?' },
  { key:'dashboard.stat_catches',     de:'Fänge',                    en:'Catches',                  fr:'Prises' },
  { key:'dashboard.stat_spots',       de:'Angelspots',               en:'Fishing Spots',            fr:'Spots' },
  { key:'dashboard.stat_species',     de:'Fischarten',               en:'Fish species',             fr:'Espèces' },
  { key:'dashboard.stat_best',        de:'Bester Fang',              en:'Best catch',               fr:'Meilleure prise' },
  { key:'dashboard.recent_catches',   de:'Letzte Fänge',             en:'Recent catches',           fr:'Dernières prises' },
  { key:'dashboard.no_catches',       de:'Noch keine Fänge eingetragen.',  en:'No catches logged yet.', fr:'Aucune prise enregistrée.' },
  { key:'dashboard.add_catch',        de:'Fang eintragen',           en:'Log catch',                fr:'Enregistrer une prise' },
  { key:'dashboard.quick_actions',    de:'Schnellaktionen',          en:'Quick actions',            fr:'Actions rapides' },
  { key:'dashboard.explore_spots',    de:'Spots entdecken',          en:'Explore spots',            fr:'Explorer les spots' },
  { key:'dashboard.check_forecast',   de:'Bissindex prüfen',         en:'Check bite index',         fr:'Vérifier l\'indice' },
  { key:'dashboard.facts_title',      de:'Wusstest du?',             en:'Did you know?',            fr:'Le saviez-vous ?' },
  { key:'dashboard.fact1',            de:'Ein Hecht kann bis zu 1,5 Meter lang werden.', en:'A pike can grow up to 1.5 metres long.', fr:'Un brochet peut atteindre 1,5 mètre de long.' },
  { key:'dashboard.fact2',            de:'Karpfen können über 40 Jahre alt werden.', en:'Carp can live for over 40 years.', fr:'Les carpes peuvent vivre plus de 40 ans.' },
  { key:'dashboard.fact3',            de:'Der Wels ist der größte Süßwasserfisch Europas.', en:'The catfish is the largest freshwater fish in Europe.', fr:'Le silure est le plus grand poisson d\'eau douce d\'Europe.' },
  { key:'dashboard.weather_title',    de:'Aktuelles Wetter',         en:'Current weather',          fr:'Météo actuelle' },
  { key:'dashboard.weather_loading',  de:'Wetter wird geladen…',     en:'Loading weather…',         fr:'Chargement météo…' },
  { key:'dashboard.weather_error',    de:'Wetter konnte nicht geladen werden.', en:'Weather could not be loaded.', fr:'Météo non disponible.' },
  { key:'dashboard.cotw_title',       de:'Fang der Woche',           en:'Catch of the week',        fr:'Prise de la semaine' },
  { key:'dashboard.no_cotw',          de:'Noch kein Fang der Woche.',en:'No catch of the week yet.',fr:'Pas encore de prise de la semaine.' },

  // catches
  { key:'catches.title',           de:'Fangbuch',              en:'Catch Log',             fr:'Journal de pêche' },
  { key:'catches.subtitle',        de:'Alle deine Fänge auf einen Blick.', en:'All your catches at a glance.', fr:'Toutes vos prises en un coup d\'œil.' },
  { key:'catches.add_btn',         de:'Fang eintragen',        en:'Log catch',             fr:'Enregistrer une prise' },
  { key:'catches.search_ph',       de:'Nach Fischart oder Gewässer suchen…', en:'Search by species or water…', fr:'Rechercher par espèce ou plan d\'eau…' },
  { key:'catches.no_results',      de:'Keine Fänge gefunden.',  en:'No catches found.',     fr:'Aucune prise trouvée.' },
  { key:'catches.no_catches',      de:'Noch keine Fänge eingetragen.', en:'No catches logged yet.', fr:'Aucune prise enregistrée.' },
  { key:'catches.form_title_add',  de:'Neuen Fang eintragen',  en:'Log new catch',         fr:'Enregistrer une nouvelle prise' },
  { key:'catches.form_title_edit', de:'Fang bearbeiten',       en:'Edit catch',            fr:'Modifier la prise' },
  { key:'catches.field_species',   de:'Fischart',              en:'Fish species',          fr:'Espèce de poisson' },
  { key:'catches.field_weight',    de:'Gewicht (kg)',          en:'Weight (kg)',           fr:'Poids (kg)' },
  { key:'catches.field_length',    de:'Länge (cm)',            en:'Length (cm)',           fr:'Longueur (cm)' },
  { key:'catches.field_water',     de:'Gewässer',              en:'Water body',            fr:'Plan d\'eau' },
  { key:'catches.field_date',      de:'Datum & Uhrzeit',       en:'Date & time',           fr:'Date & heure' },
  { key:'catches.field_bait',      de:'Köder',                 en:'Bait',                  fr:'Appât' },
  { key:'catches.field_technique', de:'Technik',               en:'Technique',             fr:'Technique' },
  { key:'catches.field_notes',     de:'Notizen',               en:'Notes',                 fr:'Notes' },
  { key:'catches.field_photo',     de:'Foto',                  en:'Photo',                 fr:'Photo' },
  { key:'catches.field_visibility',de:'Sichtbarkeit',          en:'Visibility',            fr:'Visibilité' },
  { key:'catches.species_ph',      de:'z.B. Hecht, Barsch…',  en:'e.g. Pike, Perch…',    fr:'p.ex. Brochet, Perche…' },
  { key:'catches.water_ph',        de:'z.B. Müggelsee',        en:'e.g. Lake Müggelssee', fr:'p.ex. Lac Müggelssee' },
  { key:'catches.bait_ph',         de:'z.B. Gummifisch',       en:'e.g. Rubber fish',     fr:'p.ex. Poisson en caoutchouc' },
  { key:'catches.technique_ph',    de:'z.B. Spinnfischen',     en:'e.g. Spinning',        fr:'p.ex. Pêche au lancer' },
  { key:'catches.notes_ph',        de:'Optionale Notizen…',    en:'Optional notes…',      fr:'Notes facultatives…' },
  { key:'catches.photo_hint',      de:'Bild auswählen oder hierher ziehen', en:'Select or drag image here', fr:'Sélectionner ou glisser l\'image ici' },
  { key:'catches.delete_confirm',  de:'Diesen Fang wirklich löschen?', en:'Really delete this catch?', fr:'Supprimer vraiment cette prise ?' },
  { key:'catches.saved',           de:'Fang gespeichert!',     en:'Catch saved!',          fr:'Prise enregistrée !' },
  { key:'catches.deleted',         de:'Fang gelöscht.',        en:'Catch deleted.',        fr:'Prise supprimée.' },
  { key:'catches.detail_title',    de:'Fang-Details',          en:'Catch details',         fr:'Détails de la prise' },
  { key:'catches.sort_date',       de:'Nach Datum',            en:'By date',               fr:'Par date' },
  { key:'catches.sort_weight',     de:'Nach Gewicht',          en:'By weight',             fr:'Par poids' },
  { key:'catches.filter_species',  de:'Alle Arten',            en:'All species',           fr:'Toutes les espèces' },

  // spots
  { key:'spots.title',             de:'Angelspots',             en:'Fishing Spots',          fr:'Spots de pêche' },
  { key:'spots.subtitle',          de:'Deine besten Plätze.',   en:'Your best spots.',       fr:'Vos meilleurs spots.' },
  { key:'spots.add_btn',           de:'Spot hinzufügen',        en:'Add spot',               fr:'Ajouter un spot' },
  { key:'spots.no_spots',          de:'Noch keine Spots gespeichert.', en:'No spots saved yet.', fr:'Aucun spot enregistré.' },
  { key:'spots.no_results',        de:'Keine Spots gefunden.',  en:'No spots found.',        fr:'Aucun spot trouvé.' },
  { key:'spots.search_ph',         de:'Nach Name oder Beschreibung suchen…', en:'Search by name or description…', fr:'Rechercher par nom ou description…' },
  { key:'spots.form_title_add',    de:'Neuen Spot hinzufügen',  en:'Add new spot',           fr:'Ajouter un nouveau spot' },
  { key:'spots.form_title_edit',   de:'Spot bearbeiten',        en:'Edit spot',              fr:'Modifier le spot' },
  { key:'spots.field_title',       de:'Name des Spots',         en:'Spot name',              fr:'Nom du spot' },
  { key:'spots.field_desc',        de:'Beschreibung',           en:'Description',            fr:'Description' },
  { key:'spots.field_lat',         de:'Breitengrad',            en:'Latitude',               fr:'Latitude' },
  { key:'spots.field_lng',         de:'Längengrad',             en:'Longitude',              fr:'Longitude' },
  { key:'spots.field_visibility',  de:'Sichtbarkeit',           en:'Visibility',             fr:'Visibilité' },
  { key:'spots.field_species',     de:'Zielarten',              en:'Target species',         fr:'Espèces cibles' },
  { key:'spots.title_ph',          de:'z.B. Schilfkante Nord',  en:'e.g. Northern reed bank', fr:'p.ex. Berge nord de roseaux' },
  { key:'spots.desc_ph',           de:'Was macht diesen Spot besonders?', en:'What makes this spot special?', fr:'Qu\'est-ce qui rend ce spot spécial ?' },
  { key:'spots.species_ph',        de:'z.B. Hecht, Barsch',    en:'e.g. Pike, Perch',       fr:'p.ex. Brochet, Perche' },
  { key:'spots.gps_btn',           de:'GPS-Position ermitteln', en:'Get GPS position',       fr:'Obtenir la position GPS' },
  { key:'spots.gps_loading',       de:'Position wird ermittelt…', en:'Getting position…',   fr:'Obtention de la position…' },
  { key:'spots.gps_error',         de:'GPS-Position konnte nicht ermittelt werden.', en:'GPS position could not be determined.', fr:'Impossible de déterminer la position GPS.' },
  { key:'spots.delete_confirm',    de:'Diesen Spot wirklich löschen?', en:'Really delete this spot?', fr:'Supprimer vraiment ce spot ?' },
  { key:'spots.saved',             de:'Spot gespeichert!',      en:'Spot saved!',            fr:'Spot enregistré !' },
  { key:'spots.deleted',           de:'Spot gelöscht.',         en:'Spot deleted.',          fr:'Spot supprimé.' },
  { key:'spots.map_btn',           de:'In Karte anzeigen',      en:'Show on map',            fr:'Afficher sur la carte' },
  { key:'spots.map_open',          de:'Karte öffnen',           en:'Open map',               fr:'Ouvrir la carte' },
  { key:'spots.visibility_private',de:'Privat',                 en:'Private',                fr:'Privé' },
  { key:'spots.visibility_friends',de:'Freunde',                en:'Friends',                fr:'Amis' },
  { key:'spots.visibility_public', de:'Öffentlich',             en:'Public',                 fr:'Public' },
  { key:'spots.nearby_title',      de:'Spots in der Nähe',      en:'Nearby spots',           fr:'Spots à proximité' },
  { key:'spots.filter_vis',        de:'Alle Sichtbarkeiten',    en:'All visibilities',       fr:'Toutes les visibilités' },

  // forecast
  { key:'forecast.title',          de:'Bissindex',              en:'Bite Index',             fr:'Indice de morsure' },
  { key:'forecast.subtitle',       de:'Erfahre, wann der beste Anglertag ist.', en:'Find out when the best fishing day is.', fr:'Découvrez quel est le meilleur jour pour pêcher.' },
  { key:'forecast.location_label', de:'Standort',              en:'Location',               fr:'Emplacement' },
  { key:'forecast.location_ph',    de:'Ort oder PLZ eingeben…', en:'Enter place or postcode…', fr:'Saisir un lieu ou un code postal…' },
  { key:'forecast.btn_search',     de:'Standort suchen',       en:'Search location',        fr:'Rechercher l\'emplacement' },
  { key:'forecast.btn_gps',        de:'Meinen Standort verwenden', en:'Use my location',    fr:'Utiliser ma position' },
  { key:'forecast.step1',          de:'Standort auswählen',    en:'Select location',        fr:'Choisir l\'emplacement' },
  { key:'forecast.step2',          de:'Wetterdaten werden geladen…', en:'Loading weather data…', fr:'Chargement des données météo…' },
  { key:'forecast.step3',          de:'KI analysiert die Bedingungen…', en:'AI is analysing conditions…', fr:'L\'IA analyse les conditions…' },
  { key:'forecast.result_title',   de:'Bissindex für {{location}}', en:'Bite index for {{location}}', fr:'Indice de morsure pour {{location}}' },
  { key:'forecast.score_label',    de:'Gesamtbewertung',       en:'Overall score',          fr:'Score global' },
  { key:'forecast.weather_title',  de:'Wetterbedingungen',     en:'Weather conditions',     fr:'Conditions météo' },
  { key:'forecast.analysis_title', de:'KI-Analyse',            en:'AI Analysis',            fr:'Analyse IA' },
  { key:'forecast.wind',           de:'Wind',                  en:'Wind',                   fr:'Vent' },
  { key:'forecast.humidity',       de:'Luftfeuchte',           en:'Humidity',               fr:'Humidité' },
  { key:'forecast.pressure',       de:'Luftdruck',             en:'Air pressure',           fr:'Pression atmosphérique' },
  { key:'forecast.temp',           de:'Temperatur',            en:'Temperature',            fr:'Température' },
  { key:'forecast.cloud',          de:'Bewölkung',             en:'Cloud cover',            fr:'Couverture nuageuse' },
  { key:'forecast.precip',         de:'Niederschlag',          en:'Precipitation',          fr:'Précipitations' },
  { key:'forecast.error',          de:'Bissindex konnte nicht berechnet werden.', en:'Bite index could not be calculated.', fr:'L\'indice de morsure n\'a pas pu être calculé.' },
  { key:'forecast.try_again',      de:'Erneut versuchen',      en:'Try again',              fr:'Réessayer' },
  { key:'forecast.tips_title',     de:'Angeltipps',            en:'Fishing tips',           fr:'Conseils de pêche' },

  // community
  { key:'community.title',         de:'Community',             en:'Community',              fr:'Communauté' },
  { key:'community.feed_tab',      de:'Feed',                  en:'Feed',                   fr:'Fil d\'actualité' },
  { key:'community.ranking_tab',   de:'Rangliste',             en:'Ranking',                fr:'Classement' },
  { key:'community.cotw_tab',      de:'Fang der Woche',        en:'Catch of the week',      fr:'Prise de la semaine' },
  { key:'community.no_posts',      de:'Noch keine Beiträge.',  en:'No posts yet.',          fr:'Aucun article encore.' },
  { key:'community.load_more',     de:'Mehr laden',            en:'Load more',              fr:'Charger plus' },
  { key:'community.like',          de:'Gefällt mir',           en:'Like',                   fr:'J\'aime' },
  { key:'community.comment',       de:'Kommentar',             en:'Comment',                fr:'Commentaire' },
  { key:'community.share',         de:'Teilen',                en:'Share',                  fr:'Partager' },
  { key:'community.report',        de:'Melden',                en:'Report',                 fr:'Signaler' },
  { key:'community.ranking_title', de:'Top-Angler',            en:'Top Anglers',            fr:'Meilleurs pêcheurs' },
  { key:'community.rank_pos',      de:'Platz',                 en:'Rank',                   fr:'Rang' },
  { key:'community.rank_angler',   de:'Angler',                en:'Angler',                 fr:'Pêcheur' },
  { key:'community.rank_catches',  de:'Fänge',                 en:'Catches',                fr:'Prises' },
  { key:'community.rank_weight',   de:'Gesamtgewicht',         en:'Total weight',           fr:'Poids total' },
  { key:'community.rank_best',     de:'Bester Fang',           en:'Best catch',             fr:'Meilleure prise' },
  { key:'community.no_ranking',    de:'Noch keine Daten für die Rangliste.', en:'No ranking data yet.', fr:'Pas encore de données de classement.' },
  { key:'community.cotw_title',    de:'Fang der Woche',        en:'Catch of the week',      fr:'Prise de la semaine' },
  { key:'community.cotw_none',     de:'Noch kein Fang der Woche gewählt.', en:'No catch of the week chosen yet.', fr:'Pas encore de prise de la semaine choisie.' },
  { key:'community.cotw_by',       de:'von',                   en:'by',                     fr:'par' },
  { key:'community.post_catch',    de:'Fang teilen',           en:'Share catch',            fr:'Partager une prise' },
  { key:'community.visibility_hint', de:'Du kannst Sichtbarkeit im Fangbuch ändern.', en:'You can change visibility in the catch log.', fr:'Vous pouvez modifier la visibilité dans le journal.' },
  { key:'community.comment_ph',    de:'Kommentar schreiben…',  en:'Write a comment…',       fr:'Écrire un commentaire…' },
  { key:'community.comment_send',  de:'Senden',                en:'Send',                   fr:'Envoyer' },
  { key:'community.comments_title',de:'Kommentare',            en:'Comments',               fr:'Commentaires' },
  { key:'community.no_comments',   de:'Noch keine Kommentare.', en:'No comments yet.',      fr:'Pas encore de commentaires.' },
  { key:'community.delete_post',   de:'Beitrag löschen',       en:'Delete post',            fr:'Supprimer l\'article' },
  { key:'community.delete_confirm',de:'Diesen Beitrag wirklich löschen?', en:'Really delete this post?', fr:'Supprimer vraiment cet article ?' },
  { key:'community.filter_all',    de:'Alle',                  en:'All',                    fr:'Tous' },
  { key:'community.filter_friends',de:'Freunde',               en:'Friends',                fr:'Amis' },
  { key:'community.species_badge', de:'{{species}} · {{weight}} kg', en:'{{species}} · {{weight}} kg', fr:'{{species}} · {{weight}} kg' },

  // profile
  { key:'profile.title',           de:'Mein Profil',           en:'My Profile',             fr:'Mon profil' },
  { key:'profile.edit_btn',        de:'Profil bearbeiten',     en:'Edit profile',           fr:'Modifier le profil' },
  { key:'profile.save_btn',        de:'Speichern',             en:'Save',                   fr:'Enregistrer' },
  { key:'profile.cancel_btn',      de:'Abbrechen',             en:'Cancel',                 fr:'Annuler' },
  { key:'profile.field_name',      de:'Name',                  en:'Name',                   fr:'Nom' },
  { key:'profile.field_email',     de:'E-Mail',                en:'Email',                  fr:'E-mail' },
  { key:'profile.field_region',    de:'Heimatgewässer / Region', en:'Home waters / Region', fr:'Eaux d\'origine / Région' },
  { key:'profile.field_skill',     de:'Erfahrungsstufe',       en:'Skill level',            fr:'Niveau d\'expérience' },
  { key:'profile.field_language',  de:'Sprache',               en:'Language',               fr:'Langue' },
  { key:'profile.field_bio',       de:'Über mich',             en:'About me',               fr:'À propos de moi' },
  { key:'profile.bio_ph',          de:'Erzähl etwas über dich…', en:'Tell us about yourself…', fr:'Parlez-nous de vous…' },
  { key:'profile.saved',           de:'Profil gespeichert!',   en:'Profile saved!',         fr:'Profil enregistré !' },
  { key:'profile.stats_title',     de:'Meine Statistiken',     en:'My statistics',          fr:'Mes statistiques' },
  { key:'profile.stat_catches',    de:'Fänge gesamt',          en:'Total catches',          fr:'Prises totales' },
  { key:'profile.stat_spots',      de:'Spots gespeichert',     en:'Spots saved',            fr:'Spots enregistrés' },
  { key:'profile.stat_species',    de:'Verschiedene Arten',    en:'Different species',      fr:'Espèces différentes' },
  { key:'profile.stat_weight',     de:'Gesamtgewicht',         en:'Total weight',           fr:'Poids total' },
  { key:'profile.stat_best',       de:'Bester Fang',           en:'Best catch',             fr:'Meilleure prise' },
  { key:'profile.change_pw_title', de:'Passwort ändern',       en:'Change password',        fr:'Changer le mot de passe' },
  { key:'profile.current_pw',      de:'Aktuelles Passwort',    en:'Current password',       fr:'Mot de passe actuel' },
  { key:'profile.new_pw',          de:'Neues Passwort',        en:'New password',           fr:'Nouveau mot de passe' },
  { key:'profile.confirm_pw',      de:'Passwort bestätigen',   en:'Confirm password',       fr:'Confirmer le mot de passe' },
  { key:'profile.change_pw_btn',   de:'Passwort ändern',       en:'Change password',        fr:'Changer le mot de passe' },
  { key:'profile.pw_changed',      de:'Passwort erfolgreich geändert!', en:'Password changed successfully!', fr:'Mot de passe modifié avec succès !' },
  { key:'profile.pw_mismatch',     de:'Die Passwörter stimmen nicht überein.', en:'Passwords do not match.', fr:'Les mots de passe ne correspondent pas.' },
  { key:'profile.delete_account',  de:'Konto löschen',         en:'Delete account',         fr:'Supprimer le compte' },
  { key:'profile.delete_confirm',  de:'Konto wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.', en:'Really delete account? This action cannot be undone.', fr:'Supprimer vraiment le compte ? Cette action est irréversible.' },
  { key:'profile.member_since',    de:'Mitglied seit',         en:'Member since',           fr:'Membre depuis' },
  { key:'profile.last_catch',      de:'Letzter Fang',          en:'Last catch',             fr:'Dernière prise' },

  // admin
  { key:'admin.title',             de:'Admin-Panel',           en:'Admin Panel',            fr:'Panneau d\'administration' },
  { key:'admin.tab_reports',       de:'🚩 Meldungen',          en:'🚩 Reports',              fr:'🚩 Signalements' },
  { key:'admin.tab_users',         de:'👥 Nutzer',              en:'👥 Users',                fr:'👥 Utilisateurs' },
  { key:'admin.tab_smtp',          de:'📧 SMTP',                en:'📧 SMTP',                 fr:'📧 SMTP' },
  { key:'admin.tab_translations',  de:'🌐 Übersetzungen',      en:'🌐 Translations',         fr:'🌐 Traductions' },
  { key:'admin.tab_cotw',          de:'🏆 COTW',               en:'🏆 COTW',                 fr:'🏆 COTW' },
  { key:'admin.reports_title',     de:'Offene Meldungen',      en:'Open reports',           fr:'Signalements ouverts' },
  { key:'admin.no_reports',        de:'Keine offenen Meldungen.', en:'No open reports.',    fr:'Aucun signalement ouvert.' },
  { key:'admin.report_from',       de:'Von',                   en:'From',                   fr:'De' },
  { key:'admin.report_against',    de:'Gegen',                 en:'Against',                fr:'Contre' },
  { key:'admin.report_reason',     de:'Grund',                 en:'Reason',                 fr:'Motif' },
  { key:'admin.report_date',       de:'Datum',                 en:'Date',                   fr:'Date' },
  { key:'admin.report_action',     de:'Aktion',                en:'Action',                 fr:'Action' },
  { key:'admin.action_warn',       de:'Verwarnung',            en:'Warn',                   fr:'Avertir' },
  { key:'admin.action_suspend',    de:'Sperren',               en:'Suspend',                fr:'Suspendre' },
  { key:'admin.action_ban',        de:'Dauerhaft sperren',     en:'Ban',                    fr:'Bannir' },
  { key:'admin.action_dismiss',    de:'Abweisen',              en:'Dismiss',                fr:'Rejeter' },
  { key:'admin.action_activate',   de:'Aktivieren',            en:'Activate',               fr:'Activer' },
  { key:'admin.action_reset_pw',   de:'Passwort zurücksetzen', en:'Reset password',         fr:'Réinitialiser le mot de passe' },
  { key:'admin.users_title',       de:'Nutzerverwaltung',      en:'User management',        fr:'Gestion des utilisateurs' },
  { key:'admin.users_search_ph',   de:'Name oder E-Mail suchen…', en:'Search name or email…', fr:'Rechercher nom ou e-mail…' },
  { key:'admin.user_name',         de:'Name',                  en:'Name',                   fr:'Nom' },
  { key:'admin.user_email',        de:'E-Mail',                en:'Email',                  fr:'E-mail' },
  { key:'admin.user_role',         de:'Rolle',                 en:'Role',                   fr:'Rôle' },
  { key:'admin.user_skill',        de:'Level',                 en:'Level',                  fr:'Niveau' },
  { key:'admin.user_status',       de:'Status',                en:'Status',                 fr:'Statut' },
  { key:'admin.user_joined',       de:'Beigetreten',           en:'Joined',                 fr:'Inscrit' },
  { key:'admin.user_actions',      de:'Aktionen',              en:'Actions',                fr:'Actions' },
  { key:'admin.user_active',       de:'Aktiv',                 en:'Active',                 fr:'Actif' },
  { key:'admin.user_suspended',    de:'Gesperrt',              en:'Suspended',              fr:'Suspendu' },
  { key:'admin.user_banned',       de:'Dauerhaft gesperrt',    en:'Banned',                 fr:'Banni' },
  { key:'admin.smtp_title',        de:'SMTP-Konfiguration',    en:'SMTP configuration',     fr:'Configuration SMTP' },
  { key:'admin.smtp_host',         de:'Server (Host)',         en:'Server (Host)',           fr:'Serveur (Hôte)' },
  { key:'admin.smtp_port',         de:'Port',                  en:'Port',                   fr:'Port' },
  { key:'admin.smtp_user',         de:'Benutzername',          en:'Username',               fr:'Nom d\'utilisateur' },
  { key:'admin.smtp_pass',         de:'Passwort',              en:'Password',               fr:'Mot de passe' },
  { key:'admin.smtp_from',         de:'Absender-Adresse',      en:'Sender address',         fr:'Adresse d\'expédition' },
  { key:'admin.smtp_ssl',          de:'SSL verwenden',         en:'Use SSL',                fr:'Utiliser SSL' },
  { key:'admin.smtp_save',         de:'Speichern',             en:'Save',                   fr:'Enregistrer' },
  { key:'admin.smtp_test',         de:'Test-E-Mail senden',    en:'Send test email',        fr:'Envoyer un e-mail de test' },
  { key:'admin.smtp_saved',        de:'SMTP-Einstellungen gespeichert!', en:'SMTP settings saved!', fr:'Paramètres SMTP enregistrés !' },
  { key:'admin.smtp_test_ok',      de:'Test-E-Mail wurde gesendet.', en:'Test email sent.', fr:'E-mail de test envoyé.' },
  { key:'admin.smtp_test_fail',    de:'Test-E-Mail konnte nicht gesendet werden.', en:'Test email could not be sent.', fr:'Impossible d\'envoyer l\'e-mail de test.' },
  { key:'admin.trans_title',       de:'Übersetzungen verwalten', en:'Manage translations',  fr:'Gérer les traductions' },
  { key:'admin.trans_filter_ph',   de:'Namespace filtern…',    en:'Filter namespace…',      fr:'Filtrer l\'espace de noms…' },
  { key:'admin.trans_all_ns',      de:'Alle',                  en:'All',                    fr:'Tous' },
  { key:'admin.trans_key',         de:'Schlüssel',             en:'Key',                    fr:'Clé' },
  { key:'admin.trans_de',          de:'Deutsch',               en:'German',                 fr:'Allemand' },
  { key:'admin.trans_en',          de:'Englisch',              en:'English',                fr:'Anglais' },
  { key:'admin.trans_fr',          de:'Französisch',           en:'French',                 fr:'Français' },
  { key:'admin.trans_actions',     de:'Aktionen',              en:'Actions',                fr:'Actions' },
  { key:'admin.trans_add_title',   de:'Neuen Schlüssel hinzufügen', en:'Add new key',       fr:'Ajouter une nouvelle clé' },
  { key:'admin.trans_key_ph',      de:'namespace.key_name',   en:'namespace.key_name',     fr:'namespace.key_name' },
  { key:'admin.trans_add_btn',     de:'Schlüssel hinzufügen',  en:'Add key',               fr:'Ajouter la clé' },
  { key:'admin.trans_saved',       de:'Übersetzung gespeichert.', en:'Translation saved.',  fr:'Traduction enregistrée.' },
  { key:'admin.trans_deleted',     de:'Schlüssel gelöscht.',   en:'Key deleted.',           fr:'Clé supprimée.' },
  { key:'admin.trans_delete_confirm', de:'Schlüssel "{{key}}" wirklich löschen?', en:'Really delete key "{{key}}"?', fr:'Supprimer vraiment la clé "{{key}}" ?' },
  { key:'admin.cotw_title',        de:'Fang der Woche',        en:'Catch of the week',      fr:'Prise de la semaine' },
  { key:'admin.cotw_current',      de:'Aktuell',               en:'Current',                fr:'Actuel' },
  { key:'admin.cotw_set',          de:'Als COTW setzen',       en:'Set as COTW',            fr:'Définir comme COTW' },
  { key:'admin.cotw_remove',       de:'COTW entfernen',        en:'Remove COTW',            fr:'Supprimer COTW' },
  { key:'admin.cotw_none',         de:'Kein COTW gesetzt.',    en:'No COTW set.',           fr:'Aucun COTW défini.' },

  // report
  { key:'report.title',               de:'Nutzer melden',         en:'Report user',            fr:'Signaler un utilisateur' },
  { key:'report.intro_before_link',   de:'Bitte lies zuerst unsere', en:'Please read our',     fr:'Veuillez d\'abord lire nos' },
  { key:'report.intro_link',          de:'Verhaltensregeln',       en:'Community Guidelines',  fr:'règles de conduite' },
  { key:'report.intro_after_link',    de:', bevor du eine Meldung abschickst.', en:' before submitting a report.', fr:' avant d\'envoyer un signalement.' },
  { key:'report.field_username',      de:'Nutzername / E-Mail',   en:'Username / Email',       fr:'Nom d\'utilisateur / E-mail' },
  { key:'report.username_ph',         de:'Wen möchtest du melden?', en:'Who do you want to report?', fr:'Qui voulez-vous signaler ?' },
  { key:'report.field_reason',        de:'Grund',                  en:'Reason',                 fr:'Motif' },
  { key:'report.reason_spam',         de:'Spam',                   en:'Spam',                   fr:'Spam' },
  { key:'report.reason_harassment',   de:'Belästigung',            en:'Harassment',             fr:'Harcèlement' },
  { key:'report.reason_inappropriate',de:'Unangemessene Inhalte',  en:'Inappropriate content',  fr:'Contenu inapproprié' },
  { key:'report.reason_other',        de:'Sonstiges',              en:'Other',                  fr:'Autre' },
  { key:'report.field_details',       de:'Weitere Details',        en:'Additional details',     fr:'Détails supplémentaires' },
  { key:'report.details_ph',          de:'Beschreibe den Vorfall…', en:'Describe the incident…', fr:'Décrivez l\'incident…' },
  { key:'report.submit_btn',          de:'Meldung abschicken',     en:'Submit report',          fr:'Envoyer le signalement' },
  { key:'report.sending',             de:'Wird gesendet…',         en:'Sending…',               fr:'Envoi…' },
  { key:'report.success_title',       de:'Meldung eingegangen!',   en:'Report received!',       fr:'Signalement reçu !' },
  { key:'report.success_body',        de:'Wir werden den Vorfall prüfen und ggf. Maßnahmen ergreifen.', en:'We will review the incident and take appropriate action if necessary.', fr:'Nous examinerons l\'incident et prendrons les mesures appropriées si nécessaire.' },
  { key:'report.new_report',          de:'Neue Meldung',           en:'New report',             fr:'Nouveau signalement' },

  // license
  { key:'license.title',       de:'Angelschein',            en:'Fishing Licence',        fr:'Permis de pêche' },
  { key:'license.subtitle',    de:'Alles, was du über den Angelschein wissen musst.', en:'Everything you need to know about your fishing licence.', fr:'Tout ce que vous devez savoir sur votre permis de pêche.' },
  { key:'license.hero_title',  de:'Dein Weg zum Angelschein', en:'Your path to a fishing licence', fr:'Votre chemin vers le permis de pêche' },
  { key:'license.hero_body',   de:'In Deutschland brauchst du einen <strong>staatlichen Fischereischein</strong> sowie einen Erlaubnisschein des Gewässerbewirtschafters. fishing-king.de bietet dir eine einfache Online-Vorbereitung für die Fischereiprüfung.', en:'In Germany you need a <strong>state fishing licence</strong> and a permit from the water authority. fishing-king.de offers easy online preparation for the fishing exam.', fr:'En Allemagne, vous avez besoin d\'un <strong>permis de pêche d\'État</strong> et d\'une autorisation du gestionnaire des eaux. fishing-king.de propose une préparation en ligne facile à l\'examen de pêche.' },
  { key:'license.cta_btn',     de:'Zu fishing-king.de',     en:'Go to fishing-king.de',  fr:'Aller sur fishing-king.de' },
  { key:'license.steps_title', de:'In 4 Schritten zum Angelschein', en:'4 steps to your fishing licence', fr:'4 étapes pour obtenir votre permis de pêche' },
  { key:'license.step1_title', de:'Online lernen',          en:'Learn online',           fr:'Apprendre en ligne' },
  { key:'license.step1_text',  de:'Bereite dich mit Online-Kursen, Lernkarten und Prüfungssimulationen auf die Fischereiprüfung vor.', en:'Prepare for the fishing exam with online courses, flashcards and practice tests.', fr:'Préparez-vous à l\'examen de pêche avec des cours en ligne, des fiches et des simulations d\'examen.' },
  { key:'license.step2_title', de:'Prüfung ablegen',        en:'Take the exam',          fr:'Passer l\'examen' },
  { key:'license.step2_text',  de:'Die staatliche Fischereiprüfung findet beim zuständigen Amt statt und besteht aus einem schriftlichen Teil.', en:'The state fishing exam takes place at the relevant authority and consists of a written part.', fr:'L\'examen de pêche d\'État a lieu auprès de l\'autorité compétente et comprend une partie écrite.' },
  { key:'license.step3_title', de:'Fischereischein beantragen', en:'Apply for the licence', fr:'Demander le permis' },
  { key:'license.step3_text',  de:'Nach bestandener Prüfung beantragst du beim Landratsamt oder der Gemeinde deinen staatlichen Fischereischein.', en:'After passing the exam, you apply for your state fishing licence at the district office or municipality.', fr:'Après avoir réussi l\'examen, vous demandez votre permis de pêche d\'État auprès de la sous-préfecture ou de la commune.' },
  { key:'license.step4_title', de:'Erlaubnisschein kaufen',  en:'Buy a permit',           fr:'Acheter une autorisation' },
  { key:'license.step4_text',  de:'Für jedes Gewässer brauchst du zusätzlich einen Erlaubnisschein des Bewirtschafters – oft günstig beim Angelverein erhältlich.', en:'For each water you also need a permit from the operator – often available cheaply from the fishing club.', fr:'Pour chaque plan d\'eau, vous avez également besoin d\'une autorisation du gestionnaire – souvent disponible à faible coût auprès du club de pêche.' },
  { key:'license.faq_title',   de:'Häufige Fragen',         en:'Frequently asked questions', fr:'Questions fréquentes' },
  { key:'license.faq1_title',  de:'Wer braucht einen Angelschein?', en:'Who needs a fishing licence?', fr:'Qui a besoin d\'un permis de pêche ?' },
  { key:'license.faq1_text',   de:'In Deutschland benötigt jeder, der in öffentlichen Gewässern angeln möchte, einen gültigen staatlichen Fischereischein.', en:'In Germany, anyone who wants to fish in public waters needs a valid state fishing licence.', fr:'En Allemagne, toute personne souhaitant pêcher dans des eaux publiques a besoin d\'un permis de pêche d\'État valide.' },
  { key:'license.faq2_title',  de:'Gilt der Schein in ganz Deutschland?', en:'Is the licence valid throughout Germany?', fr:'Le permis est-il valable dans toute l\'Allemagne ?' },
  { key:'license.faq2_text',   de:'Der staatliche Fischereischein ist bundesweit gültig, aber jedes Bundesland hat eigene Regelungen für die Prüfung.', en:'The state fishing licence is valid throughout Germany, but each federal state has its own regulations for the exam.', fr:'Le permis de pêche d\'État est valable dans toute l\'Allemagne, mais chaque Land a ses propres réglementations pour l\'examen.' },
  { key:'license.faq3_title',  de:'Wie lange ist die Vorbereitung?', en:'How long is the preparation?', fr:'Combien de temps dure la préparation ?' },
  { key:'license.faq3_text',   de:'Mit intensivem Lernen kann man sich in 2–4 Wochen auf die Prüfung vorbereiten. Online-Plattformen helfen dabei enorm.', en:'With intensive study, you can prepare for the exam in 2–4 weeks. Online platforms help enormously.', fr:'Avec un apprentissage intensif, vous pouvez vous préparer à l\'examen en 2 à 4 semaines. Les plateformes en ligne sont d\'une grande aide.' },
  { key:'license.faq4_title',  de:'Was kostet der Angelschein?', en:'How much does the fishing licence cost?', fr:'Combien coûte le permis de pêche ?' },
  { key:'license.faq4_text',   de:'Die Kosten variieren je nach Bundesland: Die Prüfungsgebühr liegt meist zwischen 20–50 €, der Fischereischein selbst kostet weitere 10–30 €.', en:'Costs vary by federal state: the exam fee is usually between €20–50, and the fishing licence itself costs a further €10–30.', fr:'Les coûts varient selon le Land : les frais d\'examen se situent généralement entre 20 et 50 €, et le permis de pêche lui-même coûte 10 à 30 € supplémentaires.' },
  { key:'license.bottom_cta',  de:'Bereit, deinen Angelschein zu machen?', en:'Ready to get your fishing licence?', fr:'Prêt à obtenir votre permis de pêche ?' },
  { key:'license.start_btn',   de:'Jetzt starten',          en:'Start now',              fr:'Commencer maintenant' },
  { key:'license.hint',        de:'Schnell, einfach und komplett online.',  en:'Fast, easy and completely online.', fr:'Rapide, simple et entièrement en ligne.' },

  // error codes
  { key:'error.error_email_taken',         de:'Diese E-Mail-Adresse ist bereits vergeben.', en:'This email address is already taken.', fr:'Cette adresse e-mail est déjà utilisée.' },
  { key:'error.error_invalid_credentials', de:'E-Mail oder Passwort ist falsch.', en:'Email or password is incorrect.', fr:'L\'e-mail ou le mot de passe est incorrect.' },
  { key:'error.error_account_inactive',    de:'Dein Konto ist gesperrt. Kontaktiere den Support.', en:'Your account is suspended. Please contact support.', fr:'Votre compte est suspendu. Contactez le support.' },
  { key:'error.error_not_found',           de:'Die angeforderte Ressource wurde nicht gefunden.', en:'The requested resource was not found.', fr:'La ressource demandée est introuvable.' },
  { key:'error.error_unauthorized',        de:'Du bist nicht angemeldet.',          en:'You are not signed in.',          fr:'Vous n\'êtes pas connecté.' },
  { key:'error.error_forbidden',           de:'Keine Berechtigung für diese Aktion.', en:'Not authorised for this action.', fr:'Pas d\'autorisation pour cette action.' },
  { key:'error.error_validation',          de:'Bitte prüfe deine Eingaben.',        en:'Please check your inputs.',       fr:'Veuillez vérifier vos saisies.' },
  { key:'error.error_server',              de:'Serverfehler. Bitte versuche es später erneut.', en:'Server error. Please try again later.', fr:'Erreur serveur. Veuillez réessayer plus tard.' },
  { key:'error.error_reset_token_invalid', de:'Dieser Reset-Link ist ungültig oder abgelaufen.', en:'This reset link is invalid or has expired.', fr:'Ce lien de réinitialisation est invalide ou a expiré.' },
  { key:'error.error_wrong_password',      de:'Das aktuelle Passwort ist falsch.',  en:'The current password is incorrect.', fr:'Le mot de passe actuel est incorrect.' },
  { key:'error.error_report_self',         de:'Du kannst dich nicht selbst melden.', en:'You cannot report yourself.',   fr:'Vous ne pouvez pas vous signaler vous-même.' },

  // legal — impressum
  { key:'legal.impressum_title',    de:'Impressum',           en:'Legal Notice',            fr:'Mentions légales' },
  { key:'legal.impressum_s1_title', de:'Angaben gemäß § 5 TMG', en:'Information pursuant to § 5 TMG', fr:'Informations conformément au § 5 TMG' },
  { key:'legal.impressum_s1_body',  de:'Timo Hoffmann\nPrivatperson\nDeutschland', en:'Timo Hoffmann\nPrivate individual\nGermany', fr:'Timo Hoffmann\nParticulier\nAllemagne' },
  { key:'legal.impressum_s2_title', de:'Kontakt',             en:'Contact',                 fr:'Contact' },
  { key:'legal.impressum_s2_body',  de:'E-Mail: angelmate@gmx.de', en:'Email: angelmate@gmx.de', fr:'E-mail : angelmate@gmx.de' },
  { key:'legal.impressum_s3_title', de:'Verantwortlich für den Inhalt (§ 18 Abs. 2 MStV)', en:'Responsible for content (§ 18 para. 2 MStV)', fr:'Responsable du contenu (§ 18 al. 2 MStV)' },
  { key:'legal.impressum_s3_body',  de:'Timo Hoffmann\nDeutschland', en:'Timo Hoffmann\nGermany', fr:'Timo Hoffmann\nAllemagne' },
  { key:'legal.impressum_s4_title', de:'Haftungsausschluss – Haftung für Inhalte', en:'Disclaimer – Liability for content', fr:'Clause de non-responsabilité – Responsabilité pour le contenu' },
  { key:'legal.impressum_s4_body',  de:'Die Inhalte dieser Website wurden mit größtmöglicher Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte kann jedoch keine Gewähr übernommen werden. Als Dienstanbieter sind wir gemäß § 7 Abs. 1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Wir sind jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen.', en:'The content of this website has been compiled with the greatest possible care. However, no guarantee can be given for the accuracy, completeness and currency of the content. As a service provider we are responsible for our own content on these pages in accordance with § 7 para. 1 TMG. However, we are not obliged to monitor transmitted or stored third-party information.', fr:'Le contenu de ce site web a été compilé avec le plus grand soin. Cependant, aucune garantie ne peut être donnée quant à l\'exactitude, l\'exhaustivité et l\'actualité du contenu. En tant que prestataire de services, nous sommes responsables de notre propre contenu sur ces pages conformément au § 7 al. 1 TMG. Nous ne sommes toutefois pas tenus de surveiller les informations de tiers transmises ou stockées.' },
  { key:'legal.impressum_s5_title', de:'Haftungsausschluss – Haftung für Links', en:'Disclaimer – Liability for links', fr:'Clause de non-responsabilité – Responsabilité pour les liens' },
  { key:'legal.impressum_s5_body',  de:'Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar.', en:'Our website contains links to external third-party websites whose content we have no influence over. The respective provider or operator of the linked pages is always responsible for their content. Illegal content was not identifiable at the time of linking.', fr:'Notre site web contient des liens vers des sites web tiers externes sur le contenu desquels nous n\'avons aucune influence. Le fournisseur ou l\'exploitant respectif des pages liées est toujours responsable de leur contenu. Le contenu illicite n\'était pas identifiable au moment de la création du lien.' },
  { key:'legal.impressum_s6_title', de:'Urheberrecht', en:'Copyright', fr:'Droit d\'auteur' },
  { key:'legal.impressum_s6_body',  de:'Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers.', en:'The content and works created by the site operators on these pages are subject to German copyright law. Reproduction, processing, distribution and any form of commercialisation beyond the limits of copyright law require the written consent of the respective author or creator.', fr:'Le contenu et les œuvres créés par les exploitants du site sur ces pages sont soumis au droit d\'auteur allemand. La reproduction, le traitement, la diffusion et toute forme d\'exploitation au-delà des limites du droit d\'auteur nécessitent le consentement écrit de l\'auteur ou du créateur respectif.' },
  { key:'legal.impressum_s7_title', de:'Datenschutz', en:'Data protection', fr:'Protection des données' },
  { key:'legal.impressum_s7_body',  de:'Die Nutzung unserer Website ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten erhoben werden, erfolgt dies auf freiwilliger Basis. Diese Daten werden ohne ausdrückliche Zustimmung nicht an Dritte weitergegeben. Weitere Informationen findest du in unserer Datenschutzerklärung.', en:'Use of our website is generally possible without providing personal data. Where personal data is collected on our pages, this is done on a voluntary basis. This data will not be passed on to third parties without explicit consent. Further information can be found in our privacy policy.', fr:'L\'utilisation de notre site web est généralement possible sans fournir de données personnelles. Lorsque des données personnelles sont collectées sur nos pages, cela se fait sur une base volontaire. Ces données ne seront pas transmises à des tiers sans consentement explicite. De plus amples informations sont disponibles dans notre politique de confidentialité.' },
  { key:'legal.impressum_s8_title', de:'Streitbeilegung', en:'Dispute resolution', fr:'Règlement des litiges' },
  { key:'legal.impressum_s8_body',  de:'Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit:\nWir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.', en:'The European Commission provides a platform for online dispute resolution (ODR):\nWe are neither willing nor obliged to participate in dispute resolution proceedings before a consumer arbitration board.', fr:'La Commission européenne met à disposition une plateforme de règlement en ligne des litiges (RLL) :\nNous ne sommes ni disposés ni obligés de participer à des procédures de règlement des litiges devant un organe d\'arbitrage des consommateurs.' },

  // legal — guidelines
  { key:'legal.guidelines_title', de:'🎣 Verhaltensregeln', en:'🎣 Community Guidelines', fr:'🎣 Règles de conduite' },
  { key:'legal.guidelines_intro', de:'AngelMate lebt von einer respektvollen und hilfreichen Gemeinschaft. Diese Regeln gelten für alle Nutzer der Plattform.', en:'AngelMate thrives on a respectful and helpful community. These rules apply to all users of the platform.', fr:'AngelMate vit d\'une communauté respectueuse et utile. Ces règles s\'appliquent à tous les utilisateurs de la plateforme.' },
  { key:'legal.guide_r1_title',  de:'Respektvoller Umgang', en:'Respectful conduct', fr:'Conduite respectueuse' },
  { key:'legal.guide_r1_items',  de:'Behandle andere Nutzer so, wie du selbst behandelt werden möchtest.\nKritik ist willkommen – persönliche Angriffe nicht.\nDiskriminierung jeder Art wird nicht toleriert.', en:'Treat other users as you would like to be treated yourself.\nCriticism is welcome – personal attacks are not.\nDiscrimination of any kind will not be tolerated.', fr:'Traitez les autres utilisateurs comme vous aimeriez être traité.\nLa critique est la bienvenue – les attaques personnelles ne le sont pas.\nToute forme de discrimination ne sera pas tolérée.' },
  { key:'legal.guide_r2_title',  de:'Fangberichte & Fotos', en:'Catch reports & photos', fr:'Rapports de prises & photos' },
  { key:'legal.guide_r2_intro',  de:'Fangberichte sollen ehrlich und authentisch sein. Dabei gilt:', en:'Catch reports should be honest and authentic. The following applies:', fr:'Les rapports de prises doivent être honnêtes et authentiques. Les règles suivantes s\'appliquent :' },
  { key:'legal.guide_r2_bullets',de:'Keine erfundenen oder stark übertriebenen Fänge\nFotos dürfen nicht manipuliert sein\nRespektiere den Tierschutz beim Handling der Fische', en:'No invented or heavily exaggerated catches\nPhotos must not be manipulated\nRespect animal welfare when handling fish', fr:'Pas de prises inventées ou très exagérées\nLes photos ne doivent pas être manipulées\nRespectez le bien-être animal lors de la manipulation des poissons' },
  { key:'legal.guide_r3_title',  de:'Angelspots & Geheimhaltung', en:'Fishing spots & confidentiality', fr:'Spots de pêche & confidentialité' },
  { key:'legal.guide_r3_items',  de:'Teile Spots nur, wenn du das Recht dazu hast.\nRespektiere das Hausrecht an Privatgewässern.\nVerrat keine Spots anderer Nutzer ohne deren Erlaubnis.', en:'Only share spots if you have the right to do so.\nRespect private property rights at private waters.\nDo not reveal other users\' spots without their permission.', fr:'Ne partagez des spots que si vous avez le droit de le faire.\nRespectez le droit de propriété des eaux privées.\nNe révélez pas les spots d\'autres utilisateurs sans leur permission.' },
  { key:'legal.guide_r4_title',  de:'Gesetzliche Vorschriften', en:'Legal regulations', fr:'Réglementations légales' },
  { key:'legal.guide_r4_items',  de:'Angele nur mit gültigem Angelschein und Erlaubnisschein.\nHalte Schon- und Mindestmaße strikt ein.\nBeachte die Schonzeiten für alle Fischarten.\nVerlass dich nicht auf die App als alleinige Rechtsquelle.', en:'Only fish with a valid fishing licence and permit.\nStrictly observe protected seasons and minimum sizes.\nObserve closed seasons for all fish species.\nDo not rely on the app as the sole legal source.', fr:'Ne pêchez qu\'avec un permis de pêche valide et une autorisation.\nRespectez strictement les périodes de protection et les tailles minimales.\nRespectez les périodes de fermeture pour toutes les espèces de poissons.\nNe vous fiez pas à l\'application comme seule source juridique.' },
  { key:'legal.guide_r5_title',  de:'Inhalte & Urheberrecht', en:'Content & copyright', fr:'Contenu & droit d\'auteur' },
  { key:'legal.guide_r5_items',  de:'Lade nur Fotos und Texte hoch, für die du das Urheberrecht besitzt.\nKeine pornografischen, gewaltverherrlichenden oder illegalen Inhalte.\nGekennzeichnete Werbung ist nur mit vorheriger Genehmigung erlaubt.', en:'Only upload photos and texts for which you own the copyright.\nNo pornographic, glorifying violence or illegal content.\nLabelled advertising is only permitted with prior approval.', fr:'Ne téléchargez que des photos et des textes dont vous détenez le droit d\'auteur.\nPas de contenu pornographique, faisant l\'apologie de la violence ou illégal.\nLa publicité étiquetée n\'est autorisée qu\'avec une approbation préalable.' },
  { key:'legal.guide_r6_title',  de:'Datenschutz anderer Nutzer', en:'Privacy of other users', fr:'Vie privée des autres utilisateurs' },
  { key:'legal.guide_r6_items',  de:'Veröffentliche keine persönlichen Daten anderer ohne Zustimmung.\nTeile keine Standortdaten, die andere gefährden könnten.\nScreenshots von Privatnachrichten dürfen nicht ohne Erlaubnis geteilt werden.', en:'Do not publish personal data of others without consent.\nDo not share location data that could endanger others.\nScreenshots of private messages may not be shared without permission.', fr:'Ne publiez pas de données personnelles d\'autrui sans consentement.\nNe partagez pas de données de localisation pouvant mettre les autres en danger.\nLes captures d\'écran de messages privés ne peuvent pas être partagées sans permission.' },
  { key:'legal.guide_r7_title',  de:'Spam & Werbung', en:'Spam & advertising', fr:'Spam & publicité' },
  { key:'legal.guide_r7_items',  de:'Kein Massen-Posting identischer oder irrelevanter Inhalte.\nKeine unverlangte Werbung in Fangberichten oder Kommentaren.\nAffiliate-Links sind nur mit deutlicher Kennzeichnung erlaubt.', en:'No mass posting of identical or irrelevant content.\nNo unsolicited advertising in catch reports or comments.\nAffiliate links are only permitted with clear labelling.', fr:'Pas de publication en masse de contenu identique ou non pertinent.\nPas de publicité non sollicitée dans les rapports de prises ou les commentaires.\nLes liens d\'affiliation ne sont autorisés qu\'avec une identification claire.' },
  { key:'legal.guide_r8_title',  de:'Meldungen & Konsequenzen', en:'Reports & consequences', fr:'Signalements & conséquences' },
  { key:'legal.guide_r8_items',  de:'Nutze die Meldefunktion für Regelverstöße – nicht für persönliche Konflikte.\nFalschmeldungen können zum Verlust des Meldeprivilegs führen.\nBei schwerwiegenden Verstößen behalten wir uns eine dauerhafte Sperrung vor.', en:'Use the report function for rule violations – not for personal conflicts.\nFalse reports can lead to loss of reporting privilege.\nFor serious violations we reserve the right to impose a permanent ban.', fr:'Utilisez la fonction de signalement pour les infractions aux règles – pas pour les conflits personnels.\nDes signalements abusifs peuvent entraîner la perte du privilège de signalement.\nPour les infractions graves, nous nous réservons le droit de procéder à un bannissement permanent.' },
  { key:'legal.guide_r9_title',  de:'Änderungen der Regeln', en:'Changes to the rules', fr:'Modifications des règles' },
  { key:'legal.guide_r9_items',  de:'Wir behalten uns vor, diese Regeln jederzeit anzupassen.\nÄnderungen werden in der App kommuniziert.\nDie weitere Nutzung der App gilt als Zustimmung zu den aktualisierten Regeln.', en:'We reserve the right to amend these rules at any time.\nChanges will be communicated within the app.\nContinued use of the app constitutes acceptance of the updated rules.', fr:'Nous nous réservons le droit de modifier ces règles à tout moment.\nLes modifications seront communiquées dans l\'application.\nLa poursuite de l\'utilisation de l\'application vaut acceptation des règles mises à jour.' },

  // legal — privacy
  { key:'legal.privacy_title',          de:'Datenschutzerklärung',    en:'Privacy Policy',            fr:'Politique de confidentialité' },
  { key:'legal.privacy_intro',          de:'Der Schutz deiner persönlichen Daten ist uns wichtig. Nachfolgend informieren wir dich umfassend über die Erhebung, Verarbeitung und Nutzung deiner Daten.', en:'The protection of your personal data is important to us. Below we inform you comprehensively about the collection, processing and use of your data.', fr:'La protection de vos données personnelles est importante pour nous. Vous trouverez ci-dessous des informations complètes sur la collecte, le traitement et l\'utilisation de vos données.' },

  { key:'legal.privacy_s1_title',       de:'1. Verantwortlicher',      en:'1. Controller',             fr:'1. Responsable du traitement' },
  { key:'legal.privacy_s1_contact_note',de:'Bei Fragen zum Datenschutz wende dich bitte per E-Mail an uns.', en:'For questions about data protection please contact us by email.', fr:'Pour toute question relative à la protection des données, veuillez nous contacter par e-mail.' },

  { key:'legal.privacy_s2_title',       de:'2. Grundsätze der Datenverarbeitung', en:'2. Principles of data processing', fr:'2. Principes du traitement des données' },
  { key:'legal.privacy_s2_body',        de:'Wir verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung der App-Funktionen notwendig ist oder du eingewilligt hast.\nRechtsgrundlagen: Art. 6 Abs. 1 lit. b DSGVO (Vertragserfüllung), Art. 6 Abs. 1 lit. f DSGVO (berechtigte Interessen), Art. 6 Abs. 1 lit. a DSGVO (Einwilligung).\nDeine Daten werden nicht zu Werbezwecken an Dritte verkauft.', en:'We only process personal data to the extent necessary to provide the app functions or if you have consented.\nLegal bases: Art. 6(1)(b) GDPR (performance of contract), Art. 6(1)(f) GDPR (legitimate interests), Art. 6(1)(a) GDPR (consent).\nYour data is not sold to third parties for advertising purposes.', fr:'Nous ne traitons les données personnelles que dans la mesure nécessaire à la fourniture des fonctions de l\'application ou si vous avez consenti.\nBases légales : art. 6, par. 1, lit. b RGPD (exécution du contrat), art. 6, par. 1, lit. f RGPD (intérêts légitimes), art. 6, par. 1, lit. a RGPD (consentement).\nVos données ne sont pas vendues à des tiers à des fins publicitaires.' },

  { key:'legal.privacy_s3_title',       de:'3. Verarbeitete Daten',    en:'3. Data processed',         fr:'3. Données traitées' },
  { key:'legal.privacy_s3_1_title',     de:'3.1 Registrierung & Profil', en:'3.1 Registration & profile', fr:'3.1 Inscription & profil' },
  { key:'legal.privacy_s3_1_body',      de:'Bei der Registrierung erheben wir: Name, E-Mail-Adresse, Passwort (verschlüsselt), Heimatregion, Erfahrungsstufe und Sprachpräferenz.\nDiese Daten werden zur Accountverwaltung und Personalisierung der App genutzt.', en:'During registration we collect: name, email address, password (encrypted), home region, skill level and language preference.\nThis data is used for account management and personalisation of the app.', fr:'Lors de l\'inscription, nous collectons : nom, adresse e-mail, mot de passe (chiffré), région d\'origine, niveau d\'expérience et préférence linguistique.\nCes données sont utilisées pour la gestion du compte et la personnalisation de l\'application.' },
  { key:'legal.privacy_s3_2_title',     de:'3.2 Fangbuch', en:'3.2 Catch log', fr:'3.2 Journal de pêche' },
  { key:'legal.privacy_s3_2_body',      de:'Eingetragene Fänge enthalten: Fischart, Gewicht, Länge, Gewässer, Datum/Uhrzeit, Köder, Technik, optionale Notizen und optionale Fotos.\nNur du und ggf. andere Nutzer entsprechend deiner Sichtbarkeitseinstellung können deine Fänge sehen.', en:'Logged catches contain: fish species, weight, length, water body, date/time, bait, technique, optional notes and optional photos.\nOnly you and any other users according to your visibility setting can see your catches.', fr:'Les prises enregistrées contiennent : espèce de poisson, poids, longueur, plan d\'eau, date/heure, appât, technique, notes facultatives et photos facultatives.\nSeuls vous et éventuellement d\'autres utilisateurs selon votre paramètre de visibilité pouvez voir vos prises.' },
  { key:'legal.privacy_s3_3_title',     de:'3.3 Angelspots', en:'3.3 Fishing spots', fr:'3.3 Spots de pêche' },
  { key:'legal.privacy_s3_3_body',      de:'Gespeicherte Spots enthalten: Name, Beschreibung, GPS-Koordinaten und Zielarten.\nDie Sichtbarkeit (privat/Freunde/öffentlich) bestimmst du selbst.', en:'Saved spots contain: name, description, GPS coordinates and target species.\nYou determine the visibility (private/friends/public) yourself.', fr:'Les spots enregistrés contiennent : nom, description, coordonnées GPS et espèces cibles.\nVous déterminez vous-même la visibilité (privé/amis/public).' },
  { key:'legal.privacy_s3_4_title',     de:'3.4 KI-Bissindex', en:'3.4 AI bite index', fr:'3.4 Indice de morsure IA' },
  { key:'legal.privacy_s3_4_body',      de:'Wenn du den Bissindex verwendest, wird dein Standort (Koordinaten oder Ortsname) sowie aktuelle Wetterdaten an die Google Gemini AI weitergeleitet, um eine Angelprognose zu erstellen.\nDie Anfrage erfolgt serverseitig – deine IP-Adresse wird dabei nicht direkt an Google übermittelt.', en:'When you use the bite index, your location (coordinates or place name) and current weather data are forwarded to Google Gemini AI to create a fishing forecast.\nThe request is made server-side – your IP address is not transmitted directly to Google.', fr:'Lorsque vous utilisez l\'indice de morsure, votre position (coordonnées ou nom de lieu) et les données météo actuelles sont transmises à Google Gemini AI pour créer une prévision de pêche.\nLa requête est effectuée côté serveur – votre adresse IP n\'est pas transmise directement à Google.' },
  { key:'legal.privacy_s3_5_title',     de:'3.5 Community-Inhalte', en:'3.5 Community content', fr:'3.5 Contenu communautaire' },
  { key:'legal.privacy_s3_5_body',      de:'Als „öffentlich" markierte Fänge und Spots sind für alle Nutzer sichtbar und können in der Community angezeigt werden.\nKommentare und Reaktionen auf Beiträge werden gespeichert und sind für die jeweilige Zielgruppe sichtbar.', en:'Catches and spots marked as "public" are visible to all users and can be displayed in the community.\nComments and reactions to posts are saved and visible to the respective target audience.', fr:'Les prises et spots marqués comme "publics" sont visibles par tous les utilisateurs et peuvent être affichés dans la communauté.\nLes commentaires et réactions aux publications sont enregistrés et visibles par le public cible respectif.' },
  { key:'legal.privacy_s3_6_title',     de:'3.6 Meldungen', en:'3.6 Reports', fr:'3.6 Signalements' },
  { key:'legal.privacy_s3_6_body',      de:'Wenn du einen Nutzer meldest, werden der Bericht und dein Nutzerprofil für die Moderation gespeichert.\nDaten aus Meldungen werden nur zur Bearbeitung durch Administratoren verwendet.', en:'When you report a user, the report and your user profile are saved for moderation.\nData from reports is only used for processing by administrators.', fr:'Lorsque vous signalez un utilisateur, le signalement et votre profil utilisateur sont enregistrés pour la modération.\nLes données des signalements ne sont utilisées que pour le traitement par les administrateurs.' },
  { key:'legal.privacy_s3_7_title',     de:'3.7 Passwort-Reset', en:'3.7 Password reset', fr:'3.7 Réinitialisation du mot de passe' },
  { key:'legal.privacy_s3_7_body',      de:'Für den Passwort-Reset speichern wir temporär ein verschlüsseltes Token mit Ablaufzeit (15 Minuten).\nNach dem Reset wird das Token gelöscht.', en:'For password reset we temporarily store an encrypted token with an expiry time (15 minutes).\nThe token is deleted after the reset.', fr:'Pour la réinitialisation du mot de passe, nous stockons temporairement un jeton chiffré avec un délai d\'expiration (15 minutes).\nLe jeton est supprimé après la réinitialisation.' },

  { key:'legal.privacy_s4_title',       de:'4. Speicherung & Löschung', en:'4. Storage & deletion', fr:'4. Stockage & suppression' },
  { key:'legal.privacy_s4_body',        de:'Deine Daten werden auf Servern in der EU gespeichert.\nNach Kontolöschung werden alle persönlichen Daten innerhalb von 30 Tagen gelöscht.\nLog-Daten (Serverfehler) werden nach 7 Tagen automatisch gelöscht.\nBackups werden nach 30 Tagen überschrieben.', en:'Your data is stored on servers in the EU.\nAfter account deletion, all personal data will be deleted within 30 days.\nLog data (server errors) is automatically deleted after 7 days.\nBackups are overwritten after 30 days.', fr:'Vos données sont stockées sur des serveurs dans l\'UE.\nAprès la suppression du compte, toutes les données personnelles seront supprimées dans les 30 jours.\nLes données de journal (erreurs serveur) sont automatiquement supprimées après 7 jours.\nLes sauvegardes sont écrasées après 30 jours.' },

  { key:'legal.privacy_s5_title',       de:'5. Drittanbieter & Auftragsverarbeiter', en:'5. Third parties & processors', fr:'5. Tiers & sous-traitants' },
  { key:'legal.privacy_s5_intro',       de:'Folgende externe Dienste werden genutzt:', en:'The following external services are used:', fr:'Les services externes suivants sont utilisés :' },
  { key:'legal.privacy_s5_th_service',  de:'Dienst',                 en:'Service',               fr:'Service' },
  { key:'legal.privacy_s5_th_purpose',  de:'Zweck',                  en:'Purpose',               fr:'Objet' },
  { key:'legal.privacy_s5_th_data',     de:'Übermittelte Daten',     en:'Data transmitted',      fr:'Données transmises' },
  { key:'legal.privacy_s5_th_location', de:'Standort',               en:'Location',              fr:'Lieu' },
  { key:'legal.privacy_s5_th_privacy',  de:'Datenschutz',            en:'Privacy policy',        fr:'Politique de confidentialité' },
  { key:'legal.privacy_s5_r1_purpose',  de:'KI-Bissindex / Angelprognose', en:'AI bite index / fishing forecast', fr:'Indice de morsure IA / prévision de pêche' },
  { key:'legal.privacy_s5_r1_data',     de:'Koordinaten, Wetterdaten, Spracheinstellung', en:'Coordinates, weather data, language setting', fr:'Coordonnées, données météo, paramètre de langue' },
  { key:'legal.privacy_s5_r2_purpose',  de:'Wetterdaten für Bissindex', en:'Weather data for bite index', fr:'Données météo pour l\'indice de morsure' },
  { key:'legal.privacy_s5_r2_data',     de:'Koordinaten',            en:'Coordinates',           fr:'Coordonnées' },
  { key:'legal.privacy_s5_r2_location', de:'EU (Schweiz)',            en:'EU (Switzerland)',      fr:'UE (Suisse)' },
  { key:'legal.privacy_s5_r3_purpose',  de:'Geocoding (Ortsname → Koordinaten)', en:'Geocoding (place name → coordinates)', fr:'Géocodage (nom de lieu → coordonnées)' },
  { key:'legal.privacy_s5_r3_data',     de:'Suchbegriff (Ortsname)',  en:'Search term (place name)', fr:'Terme de recherche (nom de lieu)' },
  { key:'legal.privacy_s5_r4_purpose',  de:'Hintergrundbilder',      en:'Background images',    fr:'Images d\'arrière-plan' },
  { key:'legal.privacy_s5_r4_data',     de:'IP-Adresse (CDN-Anfrage)', en:'IP address (CDN request)', fr:'Adresse IP (requête CDN)' },
  { key:'legal.privacy_s5_r5_purpose',  de:'Kartenansicht für Spots', en:'Map view for spots',   fr:'Vue carte pour les spots' },
  { key:'legal.privacy_s5_r5_data',     de:'IP-Adresse, Kartensegment', en:'IP address, map segment', fr:'Adresse IP, segment de carte' },
  { key:'legal.privacy_s5_r6_purpose',  de:'Versand von Passwort-Reset-E-Mails', en:'Sending password reset emails', fr:'Envoi d\'e-mails de réinitialisation de mot de passe' },
  { key:'legal.privacy_s5_r6_data',     de:'Empfänger-E-Mail, Name, Reset-Link', en:'Recipient email, name, reset link', fr:'E-mail du destinataire, nom, lien de réinitialisation' },
  { key:'legal.privacy_s5_r6_location', de:'Deutschland (EU)',       en:'Germany (EU)',          fr:'Allemagne (UE)' },
  { key:'legal.privacy_s5_footer',      de:'Alle genannten Drittanbieter sind vertraglich zur DSGVO-konformen Verarbeitung verpflichtet (AVV).\nBei Drittanbietern außerhalb der EU sind Standardvertragsklauseln (SCC) vereinbart.', en:'All named third-party providers are contractually obligated to process data in compliance with GDPR (DPA).\nFor third-party providers outside the EU, standard contractual clauses (SCC) are agreed.', fr:'Tous les fournisseurs tiers nommés sont contractuellement tenus de traiter les données conformément au RGPD (APD).\nPour les fournisseurs tiers hors de l\'UE, des clauses contractuelles standard (SCC) sont convenues.' },

  { key:'legal.privacy_s6_title',       de:'6. Cookies & lokale Speicherung', en:'6. Cookies & local storage', fr:'6. Cookies & stockage local' },
  { key:'legal.privacy_s6_intro',       de:'Wir verwenden nur technisch notwendige Speicher-Mechanismen:', en:'We only use technically necessary storage mechanisms:', fr:'Nous n\'utilisons que des mécanismes de stockage techniquement nécessaires :' },
  { key:'legal.privacy_s6_th_name',     de:'Name',                   en:'Name',                  fr:'Nom' },
  { key:'legal.privacy_s6_th_type',     de:'Typ',                    en:'Type',                  fr:'Type' },
  { key:'legal.privacy_s6_th_purpose',  de:'Zweck',                  en:'Purpose',               fr:'Objet' },
  { key:'legal.privacy_s6_th_duration', de:'Dauer',                  en:'Duration',              fr:'Durée' },
  { key:'legal.privacy_s6_th_category', de:'Kategorie',              en:'Category',              fr:'Catégorie' },
  { key:'legal.privacy_s6_token_purpose', de:'Authentifizierung (JWT)', en:'Authentication (JWT)', fr:'Authentification (JWT)' },
  { key:'legal.privacy_s6_token_duration', de:'30 Tage',             en:'30 days',               fr:'30 jours' },
  { key:'legal.privacy_s6_token_category', de:'Notwendig',           en:'Necessary',             fr:'Nécessaire' },
  { key:'legal.privacy_s6_footer',      de:'Es werden keine Tracking-Cookies, Analyse-Cookies oder Marketing-Cookies gesetzt.\nEin Cookie-Banner ist daher nicht erforderlich.', en:'No tracking cookies, analytics cookies or marketing cookies are set.\nA cookie banner is therefore not required.', fr:'Aucun cookie de suivi, d\'analyse ou de marketing n\'est défini.\nUne bannière de cookies n\'est donc pas nécessaire.' },

  { key:'legal.privacy_s7_title',       de:'7. Standortdaten', en:'7. Location data', fr:'7. Données de localisation' },
  { key:'legal.privacy_s7_intro',       de:'Standortdaten werden nur genutzt wenn du aktiv zustimmst:', en:'Location data is only used when you actively consent:', fr:'Les données de localisation ne sont utilisées que lorsque vous consentez activement :' },
  { key:'legal.privacy_s7_bullets',     de:'Bissindex: Nur wenn du auf „Meinen Standort verwenden" klickst\nSpots: Nur wenn du auf „GPS-Position ermitteln" klickst\nDaten werden nicht im Hintergrund erfasst\nKoordinaten werden nicht dauerhaft gespeichert – nur für die aktuelle Anfrage', en:'Bite index: Only when you click "Use my location"\nSpots: Only when you click "Get GPS position"\nData is not recorded in the background\nCoordinates are not permanently stored – only for the current request', fr:'Indice de morsure : Uniquement lorsque vous cliquez sur "Utiliser ma position"\nSpots : Uniquement lorsque vous cliquez sur "Obtenir la position GPS"\nLes données ne sont pas enregistrées en arrière-plan\nLes coordonnées ne sont pas stockées de façon permanente – uniquement pour la requête en cours' },
  { key:'legal.privacy_s7_footer',      de:'Browser-API: Die Standortabfrage erfolgt über die Browser-Geolocation-API. Du wirst dabei vom Browser um Erlaubnis gefragt.', en:'Browser API: The location query is made via the browser Geolocation API. Your browser will ask for permission.', fr:'API de navigateur : La requête de localisation est effectuée via l\'API de géolocalisation du navigateur. Votre navigateur vous demandera la permission.' },

  { key:'legal.privacy_s8_title',       de:'8. Deine Rechte',         en:'8. Your rights',         fr:'8. Vos droits' },
  { key:'legal.privacy_s8_intro',       de:'Als betroffene Person hast du folgende Rechte gemäß DSGVO:', en:'As a data subject you have the following rights under the GDPR:', fr:'En tant que personne concernée, vous disposez des droits suivants au titre du RGPD :' },
  { key:'legal.privacy_s8_contact',     de:'Zur Ausübung deiner Rechte kontaktiere uns per E-Mail:', en:'To exercise your rights please contact us by email:', fr:'Pour exercer vos droits, veuillez nous contacter par e-mail :' },
  { key:'legal.privacy_right1_title',   de:'Auskunft',                en:'Access',                 fr:'Accès' },
  { key:'legal.privacy_right1_desc',    de:'Recht auf Information, welche Daten wir über dich verarbeiten (Art. 15 DSGVO)', en:'Right to information about which data we process about you (Art. 15 GDPR)', fr:'Droit à l\'information sur les données que nous traitons vous concernant (art. 15 RGPD)' },
  { key:'legal.privacy_right2_title',   de:'Berichtigung',            en:'Rectification',          fr:'Rectification' },
  { key:'legal.privacy_right2_desc',    de:'Recht auf Korrektur falscher oder unvollständiger Daten (Art. 16 DSGVO)', en:'Right to correction of incorrect or incomplete data (Art. 16 GDPR)', fr:'Droit à la correction des données inexactes ou incomplètes (art. 16 RGPD)' },
  { key:'legal.privacy_right3_title',   de:'Löschung',                en:'Erasure',                fr:'Effacement' },
  { key:'legal.privacy_right3_desc',    de:'Recht auf Löschung deiner Daten (Art. 17 DSGVO)', en:'Right to erasure of your data (Art. 17 GDPR)', fr:'Droit à la suppression de vos données (art. 17 RGPD)' },
  { key:'legal.privacy_right4_title',   de:'Einschränkung',           en:'Restriction',            fr:'Limitation' },
  { key:'legal.privacy_right4_desc',    de:'Recht auf Einschränkung der Verarbeitung (Art. 18 DSGVO)', en:'Right to restriction of processing (Art. 18 GDPR)', fr:'Droit à la limitation du traitement (art. 18 RGPD)' },
  { key:'legal.privacy_right5_title',   de:'Datenübertragbarkeit',    en:'Portability',            fr:'Portabilité' },
  { key:'legal.privacy_right5_desc',    de:'Recht auf Erhalt deiner Daten in maschinenlesbarem Format (Art. 20 DSGVO)', en:'Right to receive your data in machine-readable format (Art. 20 GDPR)', fr:'Droit de recevoir vos données dans un format lisible par machine (art. 20 RGPD)' },
  { key:'legal.privacy_right6_title',   de:'Widerspruch',             en:'Objection',              fr:'Opposition' },
  { key:'legal.privacy_right6_desc',    de:'Recht auf Widerspruch gegen die Verarbeitung (Art. 21 DSGVO)', en:'Right to object to processing (Art. 21 GDPR)', fr:'Droit de s\'opposer au traitement (art. 21 RGPD)' },
  { key:'legal.privacy_right7_title',   de:'Widerruf',                en:'Withdrawal',             fr:'Retrait' },
  { key:'legal.privacy_right7_desc',    de:'Recht auf Widerruf erteilter Einwilligungen (Art. 7 Abs. 3 DSGVO)', en:'Right to withdraw consents given (Art. 7(3) GDPR)', fr:'Droit de retirer les consentements accordés (art. 7, par. 3, RGPD)' },
  { key:'legal.privacy_right8_title',   de:'Beschwerde',              en:'Complaint',              fr:'Plainte' },
  { key:'legal.privacy_right8_desc',    de:'Recht auf Beschwerde bei einer Aufsichtsbehörde (Art. 77 DSGVO)', en:'Right to lodge a complaint with a supervisory authority (Art. 77 GDPR)', fr:'Droit de déposer une plainte auprès d\'une autorité de contrôle (art. 77 RGPD)' },

  { key:'legal.privacy_s9_title',       de:'9. Minderjährige',        en:'9. Minors',              fr:'9. Mineurs' },
  { key:'legal.privacy_s9_body',        de:'AngelMate richtet sich an Nutzer ab 16 Jahren.\nPersonen unter 16 Jahren dürfen die App nur mit Zustimmung eines Erziehungsberechtigten nutzen.\nFalls wir erfahren, dass wir Daten von Minderjährigen unter 16 Jahren verarbeitet haben, werden diese unverzüglich gelöscht.', en:'AngelMate is aimed at users aged 16 and over.\nPersons under 16 may only use the app with the consent of a parent or guardian.\nIf we become aware that we have processed data from minors under 16, this will be deleted immediately.', fr:'AngelMate s\'adresse aux utilisateurs de 16 ans et plus.\nLes personnes de moins de 16 ans ne peuvent utiliser l\'application qu\'avec le consentement d\'un parent ou tuteur.\nSi nous apprenons que nous avons traité des données de mineurs de moins de 16 ans, celles-ci seront supprimées immédiatement.' },

  { key:'legal.privacy_s10_title',      de:'10. Änderungen dieser Datenschutzerklärung', en:'10. Changes to this privacy policy', fr:'10. Modifications de la présente politique de confidentialité' },
  { key:'legal.privacy_s10_body',       de:'Wir behalten uns vor, diese Datenschutzerklärung bei Bedarf zu aktualisieren.\nDie aktuelle Version ist stets in der App abrufbar.\nBei wesentlichen Änderungen informieren wir dich per E-Mail oder In-App-Hinweis.', en:'We reserve the right to update this privacy policy as necessary.\nThe current version is always available in the app.\nFor significant changes, we will inform you by email or in-app notice.', fr:'Nous nous réservons le droit de mettre à jour la présente politique de confidentialité si nécessaire.\nLa version actuelle est toujours disponible dans l\'application.\nPour les modifications importantes, nous vous informerons par e-mail ou via une notification dans l\'application.' },
  { key:'legal.privacy_date',           de:'Stand: April 2026',        en:'Last updated: April 2026', fr:'Dernière mise à jour : avril 2026' },

  // email templates (key labels for context — actual templates are in mailer.js)
  { key:'email.reset_subject',    de:'Passwort zurücksetzen – AngelMate', en:'Reset your password – AngelMate', fr:'Réinitialisez votre mot de passe – AngelMate' },
  { key:'email.reset_heading',    de:'Passwort zurücksetzen',  en:'Reset your password',    fr:'Réinitialiser votre mot de passe' },
  { key:'email.reset_body',       de:'Hallo {{name}},\n\ndu hast eine Anfrage zum Zurücksetzen deines Passworts gestellt. Klicke auf den folgenden Link, um ein neues Passwort zu vergeben:', en:'Hello {{name}},\n\nyou have requested a password reset. Click the following link to set a new password:', fr:'Bonjour {{name}},\n\nvous avez demandé une réinitialisation de mot de passe. Cliquez sur le lien suivant pour définir un nouveau mot de passe :' },
  { key:'email.reset_button',     de:'Passwort zurücksetzen',  en:'Reset password',          fr:'Réinitialiser le mot de passe' },
  { key:'email.reset_expiry',     de:'Dieser Link ist 15 Minuten gültig.', en:'This link is valid for 15 minutes.', fr:'Ce lien est valable 15 minutes.' },
  { key:'email.reset_ignore',     de:'Falls du diese Anfrage nicht gestellt hast, kannst du diese E-Mail ignorieren.', en:'If you did not make this request, you can ignore this email.', fr:'Si vous n\'avez pas fait cette demande, vous pouvez ignorer cet e-mail.' },
];

async function main() {
  const passwordHash = await import('bcryptjs').then(m => m.default.hash('password123', 12));

  await prisma.user.upsert({
    where: { email: 'max@example.com' },
    update: {},
    create: {
      name: 'Max Angler',
      email: 'max@example.com',
      passwordHash,
      homeRegion: 'Berlin/Brandenburg',
      skillLevel: 'intermediate',
    },
  });

  // Seed translation keys — idempotent (skipDuplicates keeps admin edits)
  const rows = KEYS.flatMap((k) =>
    ['de', 'en', 'fr'].map((l) => ({ locale: l, key: k.key, value: k[l] }))
  );
  const result = await prisma.translation.createMany({ data: rows, skipDuplicates: true });
  console.log(`Seeded ${result.count} translation rows (${KEYS.length} keys × 3 locales).`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
