import bcrypt from 'bcryptjs';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const KEYS = [
  // ── common ────────────────────────────────────────────────────────────────
  { key:'common.loading',   de:'Laden…',       en:'Loading…',    fr:'Chargement…' },
  { key:'common.saving',    de:'Speichern…',   en:'Saving…',     fr:'Enregistrement…' },
  { key:'common.save',      de:'Speichern',    en:'Save',        fr:'Enregistrer' },
  { key:'common.cancel',    de:'Abbrechen',    en:'Cancel',      fr:'Annuler' },
  { key:'common.delete',    de:'Löschen',      en:'Delete',      fr:'Supprimer' },
  { key:'common.edit',      de:'Bearbeiten',   en:'Edit',        fr:'Modifier' },
  { key:'common.add',       de:'Hinzufügen',   en:'Add',         fr:'Ajouter' },
  { key:'common.remove',    de:'Entfernen',    en:'Remove',      fr:'Supprimer' },
  { key:'common.public',    de:'Öffentlich',   en:'Public',      fr:'Public' },
  { key:'common.zoom',      de:'Vergrößern',   en:'Zoom',        fr:'Agrandir' },

  // ── nav ───────────────────────────────────────────────────────────────────
  { key:'nav.dashboard',  de:'Dashboard',     en:'Dashboard',       fr:'Tableau de bord' },
  { key:'nav.catches',    de:'Fangbuch',      en:'Catch Log',       fr:'Journal de pêche' },
  { key:'nav.spots',      de:'Spots',         en:'Spots',           fr:'Spots' },
  { key:'nav.spots_full', de:'Angelspots',    en:'Fishing Spots',   fr:'Spots de pêche' },
  { key:'nav.forecast',   de:'Bissindex',     en:'Bite Index',      fr:'Indice de morsure' },
  { key:'nav.community',  de:'Community',     en:'Community',       fr:'Communauté' },
  { key:'nav.profile',    de:'Profil',        en:'Profile',         fr:'Profil' },
  { key:'nav.admin',      de:'Admin',         en:'Admin',           fr:'Admin' },
  { key:'nav.logout',     de:'Abmelden',      en:'Log out',         fr:'Se déconnecter' },
  { key:'nav.menu',       de:'Menü öffnen',   en:'Open menu',       fr:'Ouvrir le menu' },

  // ── footer ────────────────────────────────────────────────────────────────
  { key:'footer.impressum',  de:'Impressum',         en:'Legal Notice',   fr:'Mentions légales' },
  { key:'footer.guidelines', de:'Verhaltensregeln',  en:'Guidelines',     fr:'Règles de conduite' },
  { key:'footer.report',     de:'Melden',            en:'Report',         fr:'Signaler' },
  { key:'footer.privacy',    de:'Datenschutz',       en:'Privacy Policy', fr:'Confidentialité' },

  // ── skill ─────────────────────────────────────────────────────────────────
  { key:'skill.beginner',     de:'Anfänger',        en:'Beginner',      fr:'Débutant' },
  { key:'skill.intermediate', de:'Fortgeschritten', en:'Intermediate',  fr:'Intermédiaire' },
  { key:'skill.advanced',     de:'Profi',           en:'Expert',        fr:'Expert' },

  // ── auth ──────────────────────────────────────────────────────────────────
  { key:'auth.hero_line1',            de:'Dein digitales',              en:'Your digital',               fr:'Votre' },
  { key:'auth.hero_line2',            de:'Angel-Tagebuch',              en:'Fishing Diary',              fr:'Journal de pêche numérique' },
  { key:'auth.hero_subtitle',         de:'Fänge, Spots und KI-Prognosen – alles an einem Ort.', en:'Catches, spots and AI forecasts – all in one place.', fr:'Prises, spots et prévisions IA – tout en un seul endroit.' },
  { key:'auth.feature_1',             de:'📖 Fangbuch mit Fotos & Statistiken', en:'📖 Catch log with photos & statistics', fr:'📖 Journal de pêche avec photos et statistiques' },
  { key:'auth.feature_2',             de:'📍 Private und öffentliche Angelspots', en:'📍 Private and public fishing spots', fr:'📍 Spots de pêche privés et publics' },
  { key:'auth.feature_3',             de:'🤖 KI-gestützter Bissindex',     en:'🤖 AI-powered bite index',           fr:'🤖 Indice de morsure alimenté par IA' },
  { key:'auth.feature_4',             de:'🌍 Community-Feed & Rangliste',   en:'🌍 Community feed & leaderboard',    fr:'🌍 Fil communautaire et classement' },
  { key:'auth.feature_5',             de:'🏆 Fang der Woche',               en:'🏆 Catch of the week',               fr:'🏆 Prise de la semaine' },
  { key:'auth.tab_login',             de:'Anmelden',                      en:'Sign in',                    fr:'Se connecter' },
  { key:'auth.tab_register',          de:'Registrieren',                  en:'Register',                   fr:'S\'inscrire' },
  { key:'auth.login_welcome',         de:'Willkommen zurück!',            en:'Welcome back!',              fr:'Bon retour !' },
  { key:'auth.register_welcome',      de:'Konto erstellen',               en:'Create account',             fr:'Créer un compte' },
  { key:'auth.name',                  de:'Name',                          en:'Name',                       fr:'Nom' },
  { key:'auth.email',                 de:'E-Mail',                        en:'Email',                      fr:'E-mail' },
  { key:'auth.password',              de:'Passwort',                      en:'Password',                   fr:'Mot de passe' },
  { key:'auth.password_placeholder',  de:'Mindestens 8 Zeichen',          en:'At least 8 characters',      fr:'Au moins 8 caractères' },
  { key:'auth.home_region',           de:'Heimatgewässer / Region',       en:'Home waters / Region',       fr:'Eaux d\'origine / Région' },
  { key:'auth.home_region_placeholder', de:'z.B. Bayern, Müggelsee',      en:'e.g. Bavaria, Lake Müggelssee', fr:'p.ex. Bavière, Lac Müggelssee' },
  { key:'auth.skill_level',           de:'Erfahrungsstufe',               en:'Skill level',                fr:'Niveau d\'expérience' },
  { key:'auth.language',              de:'Sprache',                       en:'Language',                   fr:'Langue' },
  { key:'auth.loading',               de:'Wird verarbeitet…',             en:'Processing…',                fr:'Traitement en cours…' },
  { key:'auth.login_btn',             de:'Anmelden',                      en:'Sign in',                    fr:'Se connecter' },
  { key:'auth.register_btn',          de:'Registrieren',                  en:'Register',                   fr:'S\'inscrire' },
  { key:'auth.forgot_password',       de:'Passwort vergessen?',           en:'Forgot password?',           fr:'Mot de passe oublié ?' },
  { key:'auth.forgot_intro',          de:'Gib deine E-Mail-Adresse ein. Du erhältst einen Reset-Link, falls ein Konto existiert.', en:'Enter your email address. You will receive a reset link if an account exists.', fr:'Saisissez votre adresse e-mail. Vous recevrez un lien de réinitialisation si un compte existe.' },
  { key:'auth.forgot_send_btn',       de:'Reset-Link anfordern',          en:'Request reset link',         fr:'Demander le lien de réinitialisation' },
  { key:'auth.forgot_sent_title',     de:'E-Mail gesendet!',              en:'Email sent!',                fr:'E-mail envoyé !' },
  { key:'auth.forgot_sent_body',      de:'Falls ein Konto mit dieser Adresse existiert, erhältst du in Kürze einen Reset-Link.', en:'If an account exists for this address, you will receive a reset link shortly.', fr:'Si un compte existe pour cette adresse, vous recevrez un lien de réinitialisation sous peu.' },
  { key:'auth.back_to_login',         de:'Zurück zur Anmeldung',          en:'Back to sign in',            fr:'Retour à la connexion' },
  { key:'auth.account_blocked',       de:'Konto gesperrt',                en:'Account suspended',          fr:'Compte suspendu' },
  { key:'auth.reset_title',           de:'Neues Passwort festlegen',      en:'Set new password',           fr:'Définir un nouveau mot de passe' },
  { key:'auth.reset_new_pw',          de:'Neues Passwort',                en:'New password',               fr:'Nouveau mot de passe' },
  { key:'auth.reset_confirm_pw',      de:'Passwort bestätigen',           en:'Confirm password',           fr:'Confirmer le mot de passe' },
  { key:'auth.reset_pw_ph',           de:'Mindestens 8 Zeichen',          en:'At least 8 characters',      fr:'Au moins 8 caractères' },
  { key:'auth.reset_confirm_ph',      de:'Passwort wiederholen',          en:'Repeat password',            fr:'Répéter le mot de passe' },
  { key:'auth.reset_btn',             de:'Passwort speichern',            en:'Save password',              fr:'Enregistrer le mot de passe' },
  { key:'auth.reset_loading',         de:'Speichere…',                    en:'Saving…',                    fr:'Enregistrement…' },
  { key:'auth.reset_done_title',      de:'Passwort geändert!',            en:'Password changed!',          fr:'Mot de passe modifié !' },
  { key:'auth.reset_done_body',       de:'Du kannst dich jetzt mit deinem neuen Passwort anmelden.', en:'You can now sign in with your new password.', fr:'Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.' },
  { key:'auth.reset_go_login',        de:'Zur Anmeldung',                 en:'Go to sign in',              fr:'Aller à la connexion' },
  { key:'auth.reset_err_mismatch',    de:'Die Passwörter stimmen nicht überein.', en:'Passwords do not match.', fr:'Les mots de passe ne correspondent pas.' },
  { key:'auth.reset_err_short',       de:'Das Passwort muss mindestens 8 Zeichen lang sein.', en:'Password must be at least 8 characters.', fr:'Le mot de passe doit contenir au moins 8 caractères.' },
  { key:'auth.reset_err_no_token',    de:'Ungültiger oder fehlender Reset-Token.', en:'Invalid or missing reset token.', fr:'Jeton de réinitialisation invalide ou manquant.' },

  // ── dashboard ─────────────────────────────────────────────────────────────
  { key:'dashboard.greeting',       de:'Hallo, {{name}}! 👋',         en:'Hello, {{name}}! 👋',         fr:'Bonjour, {{name}} ! 👋' },
  { key:'dashboard.catches_badge',  de:'Fänge',                       en:'catches',                     fr:'prises' },
  { key:'dashboard.fun_fact_label', de:'Wusstest du?',                en:'Did you know?',               fr:'Le saviez-vous ?' },
  { key:'dashboard.fun_fact_0',     de:'Ein Hecht kann bis zu 1,5 Meter lang werden und über 20 Jahre alt werden.', en:'A pike can grow up to 1.5 metres long and live for over 20 years.', fr:'Un brochet peut atteindre 1,5 mètre de long et vivre plus de 20 ans.' },
  { key:'dashboard.fun_fact_1',     de:'Karpfen können über 40 Jahre alt werden – manche sogar über 80 Jahre!', en:'Carp can live for over 40 years – some even over 80!', fr:'Les carpes peuvent vivre plus de 40 ans – certaines même plus de 80 !' },
  { key:'dashboard.fun_fact_2',     de:'Der Wels ist der größte Süßwasserfisch Europas und kann über 2 Meter lang werden.', en:'The catfish is the largest freshwater fish in Europe and can grow over 2 metres long.', fr:'Le silure est le plus grand poisson d\'eau douce d\'Europe et peut dépasser 2 mètres.' },
  { key:'dashboard.fun_fact_3',     de:'Forellen benötigen sehr sauberes, sauerstoffreiches Wasser – sie sind ein Zeichen für Gewässerqualität.', en:'Trout require very clean, oxygen-rich water – they are an indicator of water quality.', fr:'Les truites ont besoin d\'une eau très propre et riche en oxygène – elles sont un indicateur de la qualité de l\'eau.' },
  { key:'dashboard.fun_fact_4',     de:'Barsche haben zwei Rückenflossen – die vordere mit scharfen Stacheln schützt sie vor Raubtieren.', en:'Perch have two dorsal fins – the front one with sharp spines protects them from predators.', fr:'Les perches ont deux nageoires dorsales – la première, dotée d\'épines acérées, les protège des prédateurs.' },
  { key:'dashboard.stat_total',     de:'Fänge gesamt',                en:'Total catches',               fr:'Prises totales' },
  { key:'dashboard.stat_favorite',  de:'Lieblingsart',                en:'Favourite species',           fr:'Espèce préférée' },
  { key:'dashboard.stat_heaviest',  de:'Schwerster Fang',             en:'Heaviest catch',              fr:'Prise la plus lourde' },
  { key:'dashboard.stat_longest',   de:'Längster Fang',               en:'Longest catch',               fr:'Prise la plus longue' },
  { key:'dashboard.recent_catches', de:'Letzte Fänge',                en:'Recent catches',              fr:'Dernières prises' },
  { key:'dashboard.show_all',       de:'Alle anzeigen',               en:'Show all',                    fr:'Tout afficher' },
  { key:'dashboard.empty_catches',  de:'Noch keine Fänge eingetragen.', en:'No catches logged yet.',    fr:'Aucune prise enregistrée.' },
  { key:'dashboard.add_first_catch',de:'Ersten Fang eintragen',       en:'Log first catch',             fr:'Enregistrer la première prise' },

  // ── catches ───────────────────────────────────────────────────────────────
  { key:'catches.title',            de:'Fangbuch',                    en:'Catch Log',                   fr:'Journal de pêche' },
  { key:'catches.subtitle',         de:'Alle deine Fänge auf einen Blick.', en:'All your catches at a glance.', fr:'Toutes vos prises en un coup d\'œil.' },
  { key:'catches.entry_one',        de:'Eintrag',                     en:'entry',                       fr:'entrée' },
  { key:'catches.entry_many',       de:'Einträge',                    en:'entries',                     fr:'entrées' },
  { key:'catches.add_btn',          de:'Fang eintragen',              en:'Log catch',                   fr:'Enregistrer une prise' },
  { key:'catches.loading',          de:'Fänge werden geladen…',       en:'Loading catches…',            fr:'Chargement des prises…' },
  { key:'catches.empty',            de:'Noch keine Fänge eingetragen.', en:'No catches logged yet.',    fr:'Aucune prise enregistrée.' },
  { key:'catches.add_first',        de:'Ersten Fang eintragen',       en:'Log your first catch',        fr:'Enregistrer votre première prise' },
  { key:'catches.delete_confirm',   de:'Diesen Fang wirklich löschen?', en:'Really delete this catch?', fr:'Supprimer vraiment cette prise ?' },
  { key:'catches.modal_add',        de:'Neuen Fang eintragen',        en:'Log new catch',               fr:'Enregistrer une nouvelle prise' },
  { key:'catches.modal_edit',       de:'Fang bearbeiten',             en:'Edit catch',                  fr:'Modifier la prise' },
  { key:'catches.photo_alt',        de:'Fang-Foto',                   en:'Catch photo',                 fr:'Photo de la prise' },
  { key:'catches.photo_processing', de:'Bild wird verarbeitet…',      en:'Processing image…',           fr:'Traitement de l\'image…' },
  { key:'catches.photo_add',        de:'Foto hinzufügen',             en:'Add photo',                   fr:'Ajouter une photo' },
  { key:'catches.field_species',    de:'Fischart',                    en:'Fish species',                fr:'Espèce de poisson' },
  { key:'catches.field_species_ph', de:'z.B. Hecht, Barsch…',        en:'e.g. Pike, Perch…',           fr:'p.ex. Brochet, Perche…' },
  { key:'catches.field_water',      de:'Gewässer',                    en:'Water body',                  fr:'Plan d\'eau' },
  { key:'catches.field_water_ph',   de:'z.B. Müggelsee',              en:'e.g. Lake Müggelsee',         fr:'p.ex. Lac Müggelsee' },
  { key:'catches.field_datetime',   de:'Datum & Uhrzeit',             en:'Date & time',                 fr:'Date & heure' },
  { key:'catches.field_weight',     de:'Gewicht (kg)',                 en:'Weight (kg)',                 fr:'Poids (kg)' },
  { key:'catches.field_length',     de:'Länge (cm)',                  en:'Length (cm)',                 fr:'Longueur (cm)' },
  { key:'catches.field_bait',       de:'Köder',                       en:'Bait',                        fr:'Appât' },
  { key:'catches.field_bait_ph',    de:'z.B. Gummifisch, Spinner',    en:'e.g. Rubber fish, Spinner',   fr:'p.ex. Poisson en caoutchouc, Spinner' },
  { key:'catches.field_technique',  de:'Technik',                     en:'Technique',                   fr:'Technique' },
  { key:'catches.field_technique_ph',de:'z.B. Spinnfischen, Posenangeln', en:'e.g. Spinning, Float fishing', fr:'p.ex. Pêche au lancer, Pêche au flotteur' },
  { key:'catches.field_notes',      de:'Notizen',                     en:'Notes',                       fr:'Notes' },
  { key:'catches.field_notes_ph',   de:'Optionale Notizen…',          en:'Optional notes…',             fr:'Notes facultatives…' },
  { key:'catches.make_public',      de:'Im Community-Feed teilen (öffentlich)',  en:'Share in community feed (public)', fr:'Partager dans le fil communautaire (public)' },

  // ── spots ─────────────────────────────────────────────────────────────────
  { key:'spots.title',             de:'Angelspots',                   en:'Fishing Spots',               fr:'Spots de pêche' },
  { key:'spots.subtitle',          de:'Deine besten Plätze – privat oder mit der Community geteilt.', en:'Your best spots – private or shared with the community.', fr:'Vos meilleurs spots – privés ou partagés avec la communauté.' },
  { key:'spots.loading',           de:'Spots werden geladen…',        en:'Loading spots…',              fr:'Chargement des spots…' },
  { key:'spots.empty',             de:'Noch keine Spots gespeichert.', en:'No spots saved yet.',        fr:'Aucun spot enregistré.' },
  { key:'spots.add_btn',           de:'Spot hinzufügen',              en:'Add spot',                    fr:'Ajouter un spot' },
  { key:'spots.add_first',         de:'Ersten Spot hinzufügen',       en:'Add your first spot',         fr:'Ajouter votre premier spot' },
  { key:'spots.my_section',        de:'Meine Spots',                  en:'My spots',                    fr:'Mes spots' },
  { key:'spots.my_count',          de:'{{count}} Spot(s)',            en:'{{count}} spot(s)',            fr:'{{count}} spot(s)' },
  { key:'spots.community_section', de:'Community-Spots',              en:'Community spots',             fr:'Spots communautaires' },
  { key:'spots.modal_add',         de:'Neuen Spot hinzufügen',        en:'Add new spot',                fr:'Ajouter un nouveau spot' },
  { key:'spots.modal_edit',        de:'Spot bearbeiten',              en:'Edit spot',                   fr:'Modifier le spot' },
  { key:'spots.delete_confirm',    de:'Diesen Spot wirklich löschen?', en:'Really delete this spot?',  fr:'Supprimer vraiment ce spot ?' },
  { key:'spots.field_name',        de:'Name des Spots',               en:'Spot name',                   fr:'Nom du spot' },
  { key:'spots.field_name_ph',     de:'z.B. Schilfkante Nord',        en:'e.g. Northern reed bank',     fr:'p.ex. Berge nord de roseaux' },
  { key:'spots.field_desc',        de:'Beschreibung',                 en:'Description',                 fr:'Description' },
  { key:'spots.field_desc_ph',     de:'Was macht diesen Spot besonders?', en:'What makes this spot special?', fr:'Qu\'est-ce qui rend ce spot spécial ?' },
  { key:'spots.field_coords',      de:'Koordinaten',                  en:'Coordinates',                 fr:'Coordonnées' },
  { key:'spots.field_species',     de:'Zielarten',                    en:'Target species',              fr:'Espèces cibles' },
  { key:'spots.field_species_ph',  de:'z.B. Hecht, Barsch',           en:'e.g. Pike, Perch',            fr:'p.ex. Brochet, Perche' },
  { key:'spots.field_visibility',  de:'Sichtbarkeit',                 en:'Visibility',                  fr:'Visibilité' },
  { key:'spots.field_search',      de:'Ort suchen',                   en:'Search location',             fr:'Rechercher un lieu' },
  { key:'spots.field_search_ph',   de:'Ort oder Gewässer eingeben…',  en:'Enter place or water body…',  fr:'Saisir un lieu ou un plan d\'eau…' },
  { key:'spots.search_btn',        de:'Suchen',                       en:'Search',                      fr:'Rechercher' },
  { key:'spots.searching',         de:'Suche läuft…',                 en:'Searching…',                  fr:'Recherche en cours…' },
  { key:'spots.gps_btn',           de:'GPS-Position verwenden',       en:'Use GPS position',            fr:'Utiliser la position GPS' },
  { key:'spots.gps_loading',       de:'Position wird ermittelt…',     en:'Getting position…',           fr:'Obtention de la position…' },
  { key:'spots.geo_unsupported',   de:'GPS wird von deinem Browser nicht unterstützt.', en:'GPS is not supported by your browser.', fr:'Le GPS n\'est pas pris en charge par votre navigateur.' },
  { key:'spots.geo_error',         de:'GPS-Position konnte nicht ermittelt werden.', en:'GPS position could not be determined.', fr:'Impossible de déterminer la position GPS.' },
  { key:'spots.open_maps',         de:'In Google Maps öffnen',        en:'Open in Google Maps',         fr:'Ouvrir dans Google Maps' },
  { key:'spots.private',           de:'Privat',                       en:'Private',                     fr:'Privé' },

  // ── forecast ──────────────────────────────────────────────────────────────
  { key:'forecast.title',              de:'KI-Bissindex',                  en:'AI Bite Index',              fr:'Indice de morsure IA' },
  { key:'forecast.subtitle',           de:'Erfahre, wann und wo die Fische beißen – powered by KI.', en:'Find out when and where fish will bite – powered by AI.', fr:'Découvrez quand et où les poissons mordront – propulsé par IA.' },
  { key:'forecast.step1_title',        de:'Standort ermitteln',            en:'Determine location',         fr:'Déterminer l\'emplacement' },
  { key:'forecast.step1_desc',         de:'Erlaube den Zugriff auf deinen Standort, um aktuelle Wetterdaten zu laden.', en:'Allow access to your location to load current weather data.', fr:'Autorisez l\'accès à votre emplacement pour charger les données météo actuelles.' },
  { key:'forecast.step2_title',        de:'KI-Analyse starten',            en:'Start AI analysis',          fr:'Lancer l\'analyse IA' },
  { key:'forecast.step2_desc',         de:'Die KI analysiert Wetter, Luftdruck und Jahreszeit für eine Angelprognose.', en:'The AI analyses weather, air pressure and season for a fishing forecast.', fr:'L\'IA analyse la météo, la pression atmosphérique et la saison pour une prévision de pêche.' },
  { key:'forecast.locate_btn',         de:'Meinen Standort verwenden',     en:'Use my location',            fr:'Utiliser ma position' },
  { key:'forecast.locating',           de:'Standort wird ermittelt…',      en:'Getting location…',          fr:'Obtention de la position…' },
  { key:'forecast.analyze_btn',        de:'Bissindex berechnen',           en:'Calculate bite index',       fr:'Calculer l\'indice de morsure' },
  { key:'forecast.analyzing',          de:'KI analysiert…',                en:'AI analysing…',              fr:'IA en cours d\'analyse…' },
  { key:'forecast.weather_clear',      de:'Klarer Himmel',                 en:'Clear sky',                  fr:'Ciel dégagé' },
  { key:'forecast.weather_partly_cloudy', de:'Teils bewölkt',              en:'Partly cloudy',              fr:'Partiellement nuageux' },
  { key:'forecast.weather_cloudy',     de:'Bewölkt',                       en:'Cloudy',                     fr:'Nuageux' },
  { key:'forecast.weather_rain',       de:'Regen',                         en:'Rain',                       fr:'Pluie' },
  { key:'forecast.weather_snow',       de:'Schnee',                        en:'Snow',                       fr:'Neige' },
  { key:'forecast.weather_showers',    de:'Schauer',                       en:'Showers',                    fr:'Averses' },
  { key:'forecast.weather_thunder',    de:'Gewitter',                      en:'Thunderstorm',               fr:'Orage' },
  { key:'forecast.weather_unknown',    de:'Unbekannt',                     en:'Unknown',                    fr:'Inconnu' },
  { key:'forecast.weather_temp',       de:'Temperatur',                    en:'Temperature',                fr:'Température' },
  { key:'forecast.weather_pressure',   de:'Luftdruck',                     en:'Air pressure',               fr:'Pression atmosphérique' },
  { key:'forecast.weather_wind',       de:'Wind',                          en:'Wind',                       fr:'Vent' },
  { key:'forecast.weather_clouds',     de:'Bewölkung',                     en:'Cloud cover',                fr:'Couverture nuageuse' },
  { key:'forecast.weather_humidity',   de:'Luftfeuchte',                   en:'Humidity',                   fr:'Humidité' },
  { key:'forecast.weather_uv',         de:'UV-Index',                      en:'UV index',                   fr:'Indice UV' },
  { key:'forecast.weather_load_error', de:'Wetterdaten konnten nicht geladen werden.', en:'Weather data could not be loaded.', fr:'Les données météo n\'ont pas pu être chargées.' },
  { key:'forecast.geo_denied',         de:'Standortzugriff wurde verweigert.', en:'Location access was denied.', fr:'L\'accès à la localisation a été refusé.' },
  { key:'forecast.geo_unavailable',    de:'Standort nicht verfügbar.',     en:'Location unavailable.',      fr:'Localisation indisponible.' },
  { key:'forecast.geo_timeout',        de:'Standortabfrage hat zu lange gedauert.', en:'Location request timed out.', fr:'La demande de localisation a expiré.' },
  { key:'forecast.ai_unavailable',     de:'KI nicht verfügbar',            en:'AI unavailable',             fr:'IA non disponible' },
  { key:'forecast.ai_unavailable_desc',de:'Der KI-Dienst ist aktuell nicht erreichbar. Bitte versuche es später erneut.', en:'The AI service is currently unavailable. Please try again later.', fr:'Le service IA est actuellement indisponible. Veuillez réessayer plus tard.' },
  { key:'forecast.result_best_time',   de:'Beste Angelzeit',               en:'Best fishing time',          fr:'Meilleur moment pour pêcher' },
  { key:'forecast.result_best_species',de:'Empfohlene Arten',              en:'Recommended species',        fr:'Espèces recommandées' },
  { key:'forecast.result_best_bait',   de:'Empfohlener Köder',             en:'Recommended bait',           fr:'Appât recommandé' },

  // ── community ─────────────────────────────────────────────────────────────
  { key:'community.title',             de:'Community',                     en:'Community',                  fr:'Communauté' },
  { key:'community.subtitle',          de:'Teile deine Fänge und entdecke die der anderen.', en:'Share your catches and discover others\'.', fr:'Partagez vos prises et découvrez celles des autres.' },
  { key:'community.tab_feed',          de:'Feed',                          en:'Feed',                       fr:'Fil d\'actualité' },
  { key:'community.tab_leaderboard',   de:'Rangliste',                     en:'Leaderboard',                fr:'Classement' },
  { key:'community.tab_cotw',          de:'Fang der Woche',                en:'Catch of the Week',          fr:'Prise de la semaine' },
  { key:'community.feed_desc_before',  de:'Öffentliche Fänge aus dem',     en:'Public catches from the',    fr:'Prises publiques du' },
  { key:'community.feed_desc_after',   de:'– sichtbar für alle.',          en:'– visible to everyone.',     fr:'– visibles par tous.' },
  { key:'community.feed_empty',        de:'Noch keine öffentlichen Fänge. Sei der Erste!', en:'No public catches yet. Be the first!', fr:'Aucune prise publique pour l\'instant. Soyez le premier !' },
  { key:'community.feed_loading',      de:'Feed wird geladen…',            en:'Loading feed…',              fr:'Chargement du fil…' },
  { key:'community.share_catch',       de:'Fang teilen',                   en:'Share catch',                fr:'Partager une prise' },
  { key:'community.load_more',         de:'Mehr laden',                    en:'Load more',                  fr:'Charger plus' },
  { key:'community.like',              de:'Gefällt mir',                   en:'Like',                       fr:'J\'aime' },
  { key:'community.comment',           de:'Kommentar',                     en:'Comment',                    fr:'Commentaire' },
  { key:'community.comment_placeholder',de:'Kommentar schreiben…',         en:'Write a comment…',           fr:'Écrire un commentaire…' },
  { key:'community.comments_empty',    de:'Noch keine Kommentare.',        en:'No comments yet.',           fr:'Pas encore de commentaires.' },
  { key:'community.comments_loading',  de:'Kommentare werden geladen…',    en:'Loading comments…',          fr:'Chargement des commentaires…' },
  { key:'community.cotw_title',        de:'Fang der Woche',                en:'Catch of the Week',          fr:'Prise de la semaine' },
  { key:'community.cotw_desc',         de:'Vote für deinen Lieblingsmittelfang diese Woche.', en:'Vote for your favourite catch this week.', fr:'Votez pour votre prise préférée cette semaine.' },
  { key:'community.cotw_empty',        de:'Diese Woche noch keine nominierten Fänge.', en:'No nominated catches this week yet.', fr:'Aucune prise nominée cette semaine.' },
  { key:'community.cotw_loading',      de:'Wird geladen…',                 en:'Loading…',                   fr:'Chargement…' },
  { key:'community.all_nominees',      de:'Alle Nominierten',              en:'All nominees',               fr:'Tous les nominés' },
  { key:'community.vote',              de:'Abstimmen',                     en:'Vote',                       fr:'Voter' },
  { key:'community.voted',             de:'Abgestimmt',                    en:'Voted',                      fr:'Voté' },
  { key:'community.votes',             de:'Stimmen',                       en:'votes',                      fr:'voix' },
  { key:'community.votes_total',       de:'Stimmen gesamt',                en:'votes total',                fr:'voix au total' },
  { key:'community.login_to_vote',     de:'Melde dich an, um abzustimmen.', en:'Sign in to vote.',         fr:'Connectez-vous pour voter.' },
  { key:'community.your_catch',        de:'Das ist dein eigener Fang.',    en:'This is your own catch.',    fr:'C\'est votre propre prise.' },
  { key:'community.leading',           de:'Führend',                       en:'Leading',                    fr:'En tête' },
  { key:'community.past_winners',      de:'Vergangene Gewinner',           en:'Past winners',               fr:'Anciens gagnants' },
  { key:'community.week_abbr',         de:'KW',                            en:'Week',                       fr:'Sem.' },
  { key:'community.lb_loading',        de:'Rangliste wird geladen…',       en:'Loading leaderboard…',       fr:'Chargement du classement…' },
  { key:'community.lb_empty',          de:'Noch keine Daten für die Rangliste.', en:'No leaderboard data yet.', fr:'Pas encore de données de classement.' },
  { key:'community.lb_no_region',      de:'Kein Heimatgewässer angegeben. Bitte im Profil eintragen.', en:'No home region set. Please add it in your profile.', fr:'Aucune région d\'origine définie. Veuillez l\'ajouter dans votre profil.' },
  { key:'community.lb_you',            de:'Du',                            en:'You',                        fr:'Vous' },
  { key:'community.metric_catches',    de:'Anzahl Fänge',                  en:'Number of catches',          fr:'Nombre de prises' },
  { key:'community.metric_weight',     de:'Gesamtgewicht',                 en:'Total weight',               fr:'Poids total' },
  { key:'community.metric_record',     de:'Schwerster Einzelfang',         en:'Heaviest single catch',      fr:'Prise individuelle la plus lourde' },
  { key:'community.scope_national',    de:'Gesamt',                        en:'National',                   fr:'National' },
  { key:'community.scope_local',       de:'Regional',                      en:'Regional',                   fr:'Régional' },
  { key:'community.region_label',      de:'Region',                        en:'Region',                     fr:'Région' },
  { key:'community.no_region',         de:'Kein Heimatgewässer angegeben', en:'No home region set',         fr:'Aucune région d\'origine définie' },

  // ── profile ───────────────────────────────────────────────────────────────
  { key:'profile.avatar_title',        de:'Profilbild',                    en:'Profile picture',            fr:'Photo de profil' },
  { key:'profile.avatar_hint',         de:'Quadratisches Bild empfohlen. Wird auf 128 × 128 px skaliert.', en:'Square image recommended. Scaled to 128 × 128 px.', fr:'Image carrée recommandée. Mise à l\'échelle 128 × 128 px.' },
  { key:'profile.avatar_select',       de:'Bild auswählen',                en:'Select image',               fr:'Sélectionner une image' },
  { key:'profile.avatar_saved',        de:'Profilbild gespeichert!',       en:'Profile picture saved!',     fr:'Photo de profil enregistrée !' },
  { key:'profile.avatar_removed',      de:'Profilbild entfernt.',          en:'Profile picture removed.',   fr:'Photo de profil supprimée.' },
  { key:'profile.avatar_error',        de:'Bild konnte nicht gespeichert werden.', en:'Image could not be saved.', fr:'L\'image n\'a pas pu être enregistrée.' },
  { key:'profile.avatar_change',       de:'Profilbild ändern',             en:'Change profile picture',     fr:'Changer la photo de profil' },
  { key:'profile.edit_title',          de:'Profil bearbeiten',             en:'Edit profile',               fr:'Modifier le profil' },
  { key:'profile.edit_subtitle',       de:'Name, Region und Erfahrungsstufe anpassen.', en:'Update name, region and skill level.', fr:'Mettre à jour le nom, la région et le niveau.' },
  { key:'profile.saved_ok',            de:'Profil gespeichert!',           en:'Profile saved!',             fr:'Profil enregistré !' },
  { key:'profile.pw_title',            de:'Passwort ändern',               en:'Change password',            fr:'Changer le mot de passe' },
  { key:'profile.pw_subtitle',         de:'Wähle ein sicheres Passwort mit mindestens 8 Zeichen.', en:'Choose a secure password with at least 8 characters.', fr:'Choisissez un mot de passe sécurisé d\'au moins 8 caractères.' },
  { key:'profile.pw_current',          de:'Aktuelles Passwort',            en:'Current password',           fr:'Mot de passe actuel' },
  { key:'profile.pw_new',              de:'Neues Passwort',                en:'New password',               fr:'Nouveau mot de passe' },
  { key:'profile.pw_confirm',          de:'Passwort bestätigen',           en:'Confirm password',           fr:'Confirmer le mot de passe' },
  { key:'profile.pw_repeat',           de:'Passwort wiederholen',          en:'Repeat password',            fr:'Répéter le mot de passe' },
  { key:'profile.pw_btn',              de:'Passwort ändern',               en:'Change password',            fr:'Changer le mot de passe' },
  { key:'profile.pw_changed_ok',       de:'Passwort erfolgreich geändert!', en:'Password changed successfully!', fr:'Mot de passe modifié avec succès !' },
  { key:'profile.pw_mismatch',         de:'Die Passwörter stimmen nicht überein.', en:'Passwords do not match.', fr:'Les mots de passe ne correspondent pas.' },
  { key:'profile.info_title',          de:'Kontoinformationen',            en:'Account information',        fr:'Informations du compte' },
  { key:'profile.info_subtitle',       de:'Schreibgeschützte Kontodaten.',  en:'Read-only account details.', fr:'Détails du compte en lecture seule.' },
  { key:'profile.user_id',             de:'Nutzer-ID',                     en:'User ID',                    fr:'ID utilisateur' },
  { key:'profile.member_since_label',  de:'Mitglied seit',                 en:'Member since',               fr:'Membre depuis' },
  { key:'profile.member_since',        de:'Mitglied seit {{date}}',        en:'Member since {{date}}',      fr:'Membre depuis {{date}}' },
  { key:'profile.logout_title',        de:'Abmelden',                      en:'Sign out',                   fr:'Se déconnecter' },
  { key:'profile.logout_subtitle',     de:'Du wirst auf der aktuellen Seite abgemeldet.', en:'You will be signed out on this device.', fr:'Vous serez déconnecté sur cet appareil.' },

  // ── admin ─────────────────────────────────────────────────────────────────
  { key:'admin.title',                 de:'Admin-Panel',                   en:'Admin Panel',                fr:'Panneau d\'administration' },
  { key:'admin.subtitle',              de:'Verwaltung von Meldungen, Nutzern und Einstellungen.', en:'Manage reports, users and settings.', fr:'Gestion des signalements, utilisateurs et paramètres.' },
  { key:'admin.tab_reports',           de:'Meldungen',                     en:'Reports',                    fr:'Signalements' },
  { key:'admin.tab_users',             de:'Nutzer',                        en:'Users',                      fr:'Utilisateurs' },
  { key:'admin.tab_smtp',              de:'SMTP',                          en:'SMTP',                       fr:'SMTP' },
  { key:'admin.tab_translations',      de:'Übersetzungen',                 en:'Translations',               fr:'Traductions' },
  { key:'admin.reports_loading',       de:'Meldungen werden geladen…',     en:'Loading reports…',           fr:'Chargement des signalements…' },
  { key:'admin.reports_count',         de:'{{open}} offen · {{resolved}} erledigt', en:'{{open}} open · {{resolved}} resolved', fr:'{{open}} ouverts · {{resolved}} traités' },
  { key:'admin.filter_open',           de:'Offen',                         en:'Open',                       fr:'Ouverts' },
  { key:'admin.filter_resolved',       de:'Erledigt',                      en:'Resolved',                   fr:'Traités' },
  { key:'admin.filter_all',            de:'Alle',                          en:'All',                        fr:'Tous' },
  { key:'admin.no_open_reports',       de:'Keine offenen Meldungen. 🎉',   en:'No open reports. 🎉',        fr:'Aucun signalement ouvert. 🎉' },
  { key:'admin.no_entries',            de:'Keine Einträge.',               en:'No entries.',                fr:'Aucune entrée.' },
  { key:'admin.report_open',           de:'Offen',                         en:'Open',                       fr:'Ouvert' },
  { key:'admin.report_resolved',       de:'Erledigt',                      en:'Resolved',                   fr:'Traité' },
  { key:'admin.field_from',            de:'Von',                           en:'From',                       fr:'De' },
  { key:'admin.field_against',         de:'Gegen',                         en:'Against',                    fr:'Contre' },
  { key:'admin.field_reason',          de:'Grund',                         en:'Reason',                     fr:'Motif' },
  { key:'admin.field_resolved_at',     de:'Erledigt am',                   en:'Resolved at',                fr:'Traité le' },
  { key:'admin.btn_mark_resolved',     de:'Als erledigt markieren',        en:'Mark as resolved',           fr:'Marquer comme traité' },
  { key:'admin.btn_reopen',            de:'Wieder öffnen',                 en:'Reopen',                     fr:'Rouvrir' },
  { key:'admin.confirm_delete_report', de:'Meldung wirklich löschen?',     en:'Really delete this report?', fr:'Supprimer vraiment ce signalement ?' },
  { key:'admin.actions_label',         de:'Aktionen',                      en:'Actions',                    fr:'Actions' },
  { key:'admin.action_activate',       de:'Aktivieren',                    en:'Activate',                   fr:'Activer' },
  { key:'admin.action_deactivate',     de:'Deaktivieren',                  en:'Deactivate',                 fr:'Désactiver' },
  { key:'admin.action_promote',        de:'Zum Admin machen',              en:'Make admin',                 fr:'Nommer administrateur' },
  { key:'admin.action_demote',         de:'Admin-Rechte entziehen',        en:'Remove admin rights',        fr:'Retirer les droits admin' },
  { key:'admin.action_reset',          de:'Passwort zurücksetzen',         en:'Reset password',             fr:'Réinitialiser le mot de passe' },
  { key:'admin.action_delete_user',    de:'Nutzer löschen',                en:'Delete user',                fr:'Supprimer l\'utilisateur' },
  { key:'admin.users_loading',         de:'Nutzer werden geladen…',        en:'Loading users…',             fr:'Chargement des utilisateurs…' },
  { key:'admin.users_count',           de:'{{total}} Nutzer · {{inactive}} inaktiv', en:'{{total}} users · {{inactive}} inactive', fr:'{{total}} utilisateurs · {{inactive}} inactifs' },
  { key:'admin.search_placeholder',    de:'Name oder E-Mail suchen…',      en:'Search name or email…',      fr:'Rechercher nom ou e-mail…' },
  { key:'admin.col_name',              de:'Name',                          en:'Name',                       fr:'Nom' },
  { key:'admin.col_email',             de:'E-Mail',                        en:'Email',                      fr:'E-mail' },
  { key:'admin.col_status',            de:'Status',                        en:'Status',                     fr:'Statut' },
  { key:'admin.col_role',              de:'Rolle',                         en:'Role',                       fr:'Rôle' },
  { key:'admin.col_level',             de:'Level',                         en:'Level',                      fr:'Niveau' },
  { key:'admin.col_catches',           de:'Fänge',                         en:'Catches',                    fr:'Prises' },
  { key:'admin.col_spots',             de:'Spots',                         en:'Spots',                      fr:'Spots' },
  { key:'admin.col_since',             de:'Dabei seit',                    en:'Member since',               fr:'Membre depuis' },
  { key:'admin.no_users_found',        de:'Keine Nutzer gefunden.',        en:'No users found.',            fr:'Aucun utilisateur trouvé.' },
  { key:'admin.status_active',         de:'Aktiv',                         en:'Active',                     fr:'Actif' },
  { key:'admin.status_inactive',       de:'Inaktiv',                       en:'Inactive',                   fr:'Inactif' },
  { key:'admin.role_admin',            de:'Admin',                         en:'Admin',                      fr:'Admin' },
  { key:'admin.role_user',             de:'Nutzer',                        en:'User',                       fr:'Utilisateur' },
  { key:'admin.confirm_deactivate',    de:'{{name}} wirklich deaktivieren?', en:'Really deactivate {{name}}?', fr:'Vraiment désactiver {{name}} ?' },
  { key:'admin.confirm_activate',      de:'{{name}} wieder aktivieren?',   en:'Activate {{name}} again?',   fr:'Réactiver {{name}} ?' },
  { key:'admin.confirm_role_change',   de:'Rolle von {{name}} auf {{role}} ändern?', en:'Change role of {{name}} to {{role}}?', fr:'Changer le rôle de {{name}} en {{role}} ?' },
  { key:'admin.confirm_reset_email',   de:'Reset-E-Mail an {{email}} senden?', en:'Send reset email to {{email}}?', fr:'Envoyer un e-mail de réinitialisation à {{email}} ?' },
  { key:'admin.confirm_delete_user',   de:'Nutzer {{name}} wirklich löschen? Diese Aktion ist nicht rückgängig zu machen.', en:'Really delete user {{name}}? This action cannot be undone.', fr:'Vraiment supprimer l\'utilisateur {{name}} ? Cette action est irréversible.' },
  { key:'admin.smtp_loading',          de:'SMTP-Einstellungen werden geladen…', en:'Loading SMTP settings…', fr:'Chargement des paramètres SMTP…' },
  { key:'admin.smtp_title',            de:'E-Mail-Konfiguration',          en:'Email configuration',        fr:'Configuration e-mail' },
  { key:'admin.smtp_desc',             de:'Diese Einstellungen werden für den Versand von Passwort-Reset-E-Mails verwendet.', en:'These settings are used for sending password reset emails.', fr:'Ces paramètres sont utilisés pour l\'envoi des e-mails de réinitialisation de mot de passe.' },
  { key:'admin.smtp_host',             de:'Server (Host)',                  en:'Server (Host)',              fr:'Serveur (Hôte)' },
  { key:'admin.smtp_port',             de:'Port',                          en:'Port',                       fr:'Port' },
  { key:'admin.smtp_ssl_label',        de:'Verbindung',                    en:'Connection',                 fr:'Connexion' },
  { key:'admin.smtp_ssl_check',        de:'SSL/TLS verwenden (Port 465)',   en:'Use SSL/TLS (port 465)',     fr:'Utiliser SSL/TLS (port 465)' },
  { key:'admin.smtp_user',             de:'Benutzername',                  en:'Username',                   fr:'Nom d\'utilisateur' },
  { key:'admin.smtp_password',         de:'Passwort',                      en:'Password',                   fr:'Mot de passe' },
  { key:'admin.smtp_password_set',     de:'Passwort gesetzt (ausgeblendet)', en:'Password set (hidden)',    fr:'Mot de passe défini (masqué)' },
  { key:'admin.smtp_password_ph',      de:'SMTP-Passwort eingeben',        en:'Enter SMTP password',        fr:'Saisir le mot de passe SMTP' },
  { key:'admin.smtp_from_name',        de:'Absendername',                  en:'Sender name',                fr:'Nom d\'expéditeur' },
  { key:'admin.smtp_from_address',     de:'Absender-Adresse',              en:'Sender address',             fr:'Adresse d\'expéditeur' },
  { key:'admin.smtp_saving',           de:'Speichert…',                    en:'Saving…',                    fr:'Enregistrement…' },
  { key:'admin.smtp_save',             de:'Einstellungen speichern',       en:'Save settings',              fr:'Enregistrer les paramètres' },
  { key:'admin.smtp_saved',            de:'SMTP-Einstellungen gespeichert!', en:'SMTP settings saved!',    fr:'Paramètres SMTP enregistrés !' },
  { key:'admin.smtp_testing',          de:'Test wird gesendet…',           en:'Sending test…',              fr:'Envoi du test…' },
  { key:'admin.smtp_test',             de:'Test-E-Mail senden',            en:'Send test email',            fr:'Envoyer un e-mail de test' },
  { key:'admin.trans_loading',         de:'Übersetzungen werden geladen…', en:'Loading translations…',      fr:'Chargement des traductions…' },
  { key:'admin.trans_new_key',         de:'Neuen Schlüssel hinzufügen',    en:'Add new key',                fr:'Ajouter une nouvelle clé' },
  { key:'admin.trans_key_exists',      de:'Dieser Schlüssel existiert bereits.', en:'This key already exists.', fr:'Cette clé existe déjà.' },
  { key:'admin.trans_keys_count',      de:'Schlüssel',                     en:'keys',                       fr:'clés' },
  { key:'admin.trans_all_ns',          de:'Alle Namespaces',               en:'All namespaces',             fr:'Tous les espaces de noms' },
  { key:'admin.trans_col_key',         de:'Schlüssel',                     en:'Key',                        fr:'Clé' },
  { key:'admin.trans_col_de',          de:'Deutsch',                       en:'German',                     fr:'Allemand' },
  { key:'admin.trans_col_en',          de:'Englisch',                      en:'English',                    fr:'Anglais' },
  { key:'admin.trans_col_fr',          de:'Französisch',                   en:'French',                     fr:'Français' },
  { key:'admin.trans_confirm_delete',  de:'Schlüssel "{{key}}" wirklich löschen?', en:'Really delete key "{{key}}"?', fr:'Supprimer vraiment la clé "{{key}}" ?' },
  { key:'admin.trans_no_results',      de:'Keine Schlüssel gefunden.',     en:'No keys found.',             fr:'Aucune clé trouvée.' },

  // ── report ────────────────────────────────────────────────────────────────
  { key:'report.title',               de:'Nutzer melden',                 en:'Report user',                fr:'Signaler un utilisateur' },
  { key:'report.intro_before_link',   de:'Bitte lies zuerst unsere',      en:'Please read our',            fr:'Veuillez d\'abord lire nos' },
  { key:'report.intro_link',          de:'Verhaltensregeln',              en:'Community Guidelines',       fr:'règles de conduite' },
  { key:'report.intro_after_link',    de:', bevor du eine Meldung abschickst.', en:' before submitting a report.', fr:' avant d\'envoyer un signalement.' },
  { key:'report.success_title',       de:'Meldung eingegangen!',          en:'Report received!',           fr:'Signalement reçu !' },
  { key:'report.success_body',        de:'Wir werden den Vorfall prüfen und gegebenenfalls Maßnahmen ergreifen.', en:'We will review the incident and take action if necessary.', fr:'Nous examinerons l\'incident et prendrons des mesures si nécessaire.' },
  { key:'report.another',             de:'Weitere Meldung einreichen',    en:'Submit another report',      fr:'Soumettre un autre signalement' },
  { key:'report.section_sender',      de:'Deine Kontaktdaten',            en:'Your contact details',       fr:'Vos coordonnées' },
  { key:'report.section_content',     de:'Gemeldeter Nutzer',             en:'Reported user',              fr:'Utilisateur signalé' },
  { key:'report.section_reason',      de:'Beschreibung',                  en:'Description',                fr:'Description' },
  { key:'report.field_name',          de:'Dein Name',                     en:'Your name',                  fr:'Votre nom' },
  { key:'report.field_name_ph',       de:'Max Mustermann',                en:'Jane Doe',                   fr:'Jean Dupont' },
  { key:'report.field_email',         de:'Deine E-Mail',                  en:'Your email',                 fr:'Votre e-mail' },
  { key:'report.field_email_ph',      de:'name@beispiel.de',              en:'name@example.com',           fr:'nom@exemple.fr' },
  { key:'report.field_against',       de:'Gemeldeter Nutzer',             en:'Reported user',              fr:'Utilisateur signalé' },
  { key:'report.field_against_ph',    de:'Nutzername oder E-Mail',        en:'Username or email',          fr:'Nom d\'utilisateur ou e-mail' },
  { key:'report.field_against_hint',  de:'Nutzername, E-Mail-Adresse oder Beschreibung des Profils.', en:'Username, email address or profile description.', fr:'Nom d\'utilisateur, adresse e-mail ou description du profil.' },
  { key:'report.field_reason',        de:'Was ist passiert?',             en:'What happened?',             fr:'Que s\'est-il passé ?' },
  { key:'report.field_reason_ph',     de:'Beschreibe den Vorfall so detailliert wie möglich…', en:'Describe the incident in as much detail as possible…', fr:'Décrivez l\'incident aussi en détail que possible…' },
  { key:'report.field_min_chars',     de:'Mindestens 10 Zeichen.',        en:'At least 10 characters.',    fr:'Au moins 10 caractères.' },
  { key:'report.privacy_note',        de:'Deine Meldung wird vertraulich behandelt und nur vom Admin-Team eingesehen.', en:'Your report is treated confidentially and only viewed by the admin team.', fr:'Votre signalement est traité de manière confidentielle et consulté uniquement par l\'équipe admin.' },
  { key:'report.submit',              de:'Meldung abschicken',            en:'Submit report',              fr:'Envoyer le signalement' },
  { key:'report.submitting',          de:'Wird gesendet…',                en:'Sending…',                   fr:'Envoi…' },

  // ── error codes ───────────────────────────────────────────────────────────
  { key:'error.error_email_taken',         de:'Diese E-Mail-Adresse ist bereits vergeben.', en:'This email address is already taken.', fr:'Cette adresse e-mail est déjà utilisée.' },
  { key:'error.error_invalid_credentials', de:'E-Mail oder Passwort ist falsch.',           en:'Email or password is incorrect.',      fr:'L\'e-mail ou le mot de passe est incorrect.' },
  { key:'error.error_account_inactive',    de:'Dein Konto ist gesperrt. Bitte kontaktiere den Support.', en:'Your account is suspended. Please contact support.', fr:'Votre compte est suspendu. Contactez le support.' },
  { key:'error.error_not_found',           de:'Nicht gefunden.',                            en:'Not found.',                           fr:'Introuvable.' },
  { key:'error.error_reset_token_invalid', de:'Dieser Reset-Link ist ungültig oder abgelaufen.', en:'This reset link is invalid or has expired.', fr:'Ce lien de réinitialisation est invalide ou a expiré.' },
  { key:'error.error_wrong_password',      de:'Das aktuelle Passwort ist falsch.',          en:'The current password is incorrect.',    fr:'Le mot de passe actuel est incorrect.' },

  // ── legal — impressum ─────────────────────────────────────────────────────
  { key:'legal.impressum_title',    de:'Impressum',           en:'Legal Notice',            fr:'Mentions légales' },
  { key:'legal.impressum_s1_title', de:'Angaben gemäß § 5 TMG', en:'Information pursuant to § 5 TMG', fr:'Informations conformément au § 5 TMG' },
  { key:'legal.impressum_s1_body',  de:'Timo Hoffmann\nPrivatperson\nDeutschland', en:'Timo Hoffmann\nPrivate individual\nGermany', fr:'Timo Hoffmann\nParticulier\nAllemagne' },
  { key:'legal.impressum_s2_title', de:'Kontakt',             en:'Contact',                 fr:'Contact' },
  { key:'legal.impressum_s2_body',  de:'E-Mail: angelmate@gmx.de', en:'Email: angelmate@gmx.de', fr:'E-mail : angelmate@gmx.de' },
  { key:'legal.impressum_s3_title', de:'Verantwortlich für den Inhalt (§ 18 Abs. 2 MStV)', en:'Responsible for content (§ 18 para. 2 MStV)', fr:'Responsable du contenu (§ 18 al. 2 MStV)' },
  { key:'legal.impressum_s3_body',  de:'Timo Hoffmann\nDeutschland', en:'Timo Hoffmann\nGermany', fr:'Timo Hoffmann\nAllemagne' },
  { key:'legal.impressum_s4_title', de:'Haftungsausschluss – Haftung für Inhalte', en:'Disclaimer – Liability for content', fr:'Clause de non-responsabilité – Contenu' },
  { key:'legal.impressum_s4_body',  de:'Die Inhalte dieser Website wurden mit größtmöglicher Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte kann jedoch keine Gewähr übernommen werden. Als Dienstanbieter sind wir gemäß § 7 Abs. 1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich.', en:'The content of this website has been compiled with the greatest possible care. However, no guarantee can be given for the accuracy, completeness and currency of the content. As a service provider we are responsible for our own content on these pages in accordance with § 7 para. 1 TMG.', fr:'Le contenu de ce site a été compilé avec le plus grand soin. Cependant, aucune garantie ne peut être donnée quant à l\'exactitude, l\'exhaustivité et l\'actualité du contenu.' },
  { key:'legal.impressum_s5_title', de:'Haftungsausschluss – Haftung für Links', en:'Disclaimer – Liability for links', fr:'Clause de non-responsabilité – Liens' },
  { key:'legal.impressum_s5_body',  de:'Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich.', en:'Our website contains links to external third-party websites whose content we have no influence over. The respective provider or operator of the linked pages is always responsible for their content.', fr:'Notre site contient des liens vers des sites tiers sur le contenu desquels nous n\'avons aucune influence. Le fournisseur respectif est toujours responsable du contenu des pages liées.' },
  { key:'legal.impressum_s6_title', de:'Urheberrecht', en:'Copyright', fr:'Droit d\'auteur' },
  { key:'legal.impressum_s6_body',  de:'Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors.', en:'The content and works created by the site operators on these pages are subject to German copyright law. Reproduction, processing, distribution and any form of commercialisation beyond the limits of copyright law require the written consent of the respective author.', fr:'Le contenu et les œuvres créés sur ces pages sont soumis au droit d\'auteur allemand. La reproduction, le traitement et la diffusion au-delà des limites du droit d\'auteur nécessitent le consentement écrit de l\'auteur.' },
  { key:'legal.impressum_s7_title', de:'Datenschutz', en:'Data protection', fr:'Protection des données' },
  { key:'legal.impressum_s7_body',  de:'Die Nutzung unserer Website ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten erhoben werden, erfolgt dies auf freiwilliger Basis. Weitere Informationen findest du in unserer Datenschutzerklärung.', en:'Use of our website is generally possible without providing personal data. Where personal data is collected on our pages, this is done on a voluntary basis. Further information can be found in our privacy policy.', fr:'L\'utilisation de notre site est généralement possible sans fournir de données personnelles. De plus amples informations sont disponibles dans notre politique de confidentialité.' },
  { key:'legal.impressum_s8_title', de:'Streitbeilegung', en:'Dispute resolution', fr:'Règlement des litiges' },
  { key:'legal.impressum_s8_body',  de:'Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit:\nWir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.', en:'The European Commission provides a platform for online dispute resolution (ODR):\nWe are neither willing nor obliged to participate in dispute resolution proceedings before a consumer arbitration board.', fr:'La Commission européenne met à disposition une plateforme de règlement en ligne des litiges :\nNous ne sommes ni disposés ni obligés de participer à des procédures de règlement des litiges.' },

  // ── legal — guidelines ────────────────────────────────────────────────────
  { key:'legal.guidelines_title', de:'🎣 Verhaltensregeln', en:'🎣 Community Guidelines', fr:'🎣 Règles de conduite' },
  { key:'legal.guidelines_intro', de:'AngelMate lebt von einer respektvollen und hilfreichen Gemeinschaft. Diese Regeln gelten für alle Nutzer der Plattform.', en:'AngelMate thrives on a respectful and helpful community. These rules apply to all users of the platform.', fr:'AngelMate vit d\'une communauté respectueuse et utile. Ces règles s\'appliquent à tous les utilisateurs.' },
  { key:'legal.guide_r1_title',  de:'Respektvoller Umgang', en:'Respectful conduct', fr:'Conduite respectueuse' },
  { key:'legal.guide_r1_items',  de:'Behandle andere Nutzer so, wie du selbst behandelt werden möchtest.\nKritik ist willkommen – persönliche Angriffe nicht.\nDiskriminierung jeder Art wird nicht toleriert.', en:'Treat other users as you would like to be treated yourself.\nCriticism is welcome – personal attacks are not.\nDiscrimination of any kind will not be tolerated.', fr:'Traitez les autres utilisateurs comme vous aimeriez être traité.\nLa critique est bienvenue – les attaques personnelles ne le sont pas.\nToute discrimination ne sera pas tolérée.' },
  { key:'legal.guide_r2_title',  de:'Fangberichte & Fotos', en:'Catch reports & photos', fr:'Rapports de prises & photos' },
  { key:'legal.guide_r2_intro',  de:'Fangberichte sollen ehrlich und authentisch sein. Dabei gilt:', en:'Catch reports should be honest and authentic. The following applies:', fr:'Les rapports de prises doivent être honnêtes et authentiques :' },
  { key:'legal.guide_r2_bullets',de:'Keine erfundenen oder stark übertriebenen Fänge\nFotos dürfen nicht manipuliert sein\nRespektiere den Tierschutz beim Handling der Fische', en:'No invented or heavily exaggerated catches\nPhotos must not be manipulated\nRespect animal welfare when handling fish', fr:'Pas de prises inventées ou très exagérées\nLes photos ne doivent pas être manipulées\nRespectez le bien-être animal lors de la manipulation des poissons' },
  { key:'legal.guide_r3_title',  de:'Angelspots & Geheimhaltung', en:'Fishing spots & confidentiality', fr:'Spots de pêche & confidentialité' },
  { key:'legal.guide_r3_items',  de:'Teile Spots nur, wenn du das Recht dazu hast.\nRespektiere das Hausrecht an Privatgewässern.\nVerrat keine Spots anderer Nutzer ohne deren Erlaubnis.', en:'Only share spots if you have the right to do so.\nRespect private property rights at private waters.\nDo not reveal other users\' spots without their permission.', fr:'Ne partagez des spots que si vous avez le droit de le faire.\nRespectez les droits de propriété des eaux privées.\nNe révélez pas les spots d\'autres utilisateurs sans leur permission.' },
  { key:'legal.guide_r4_title',  de:'Gesetzliche Vorschriften', en:'Legal regulations', fr:'Réglementations légales' },
  { key:'legal.guide_r4_items',  de:'Angele nur mit gültigem Angelschein und Erlaubnisschein.\nHalte Schon- und Mindestmaße strikt ein.\nBeachte die Schonzeiten für alle Fischarten.\nVerlass dich nicht auf die App als alleinige Rechtsquelle.', en:'Only fish with a valid fishing licence and permit.\nStrictly observe protected seasons and minimum sizes.\nObserve closed seasons for all fish species.\nDo not rely on the app as the sole legal source.', fr:'Ne pêchez qu\'avec un permis valide.\nRespectez strictement les périodes de protection et les tailles minimales.\nRespectez les périodes de fermeture pour toutes les espèces.\nNe vous fiez pas à l\'application comme seule source juridique.' },
  { key:'legal.guide_r5_title',  de:'Inhalte & Urheberrecht', en:'Content & copyright', fr:'Contenu & droit d\'auteur' },
  { key:'legal.guide_r5_items',  de:'Lade nur Fotos und Texte hoch, für die du das Urheberrecht besitzt.\nKeine pornografischen, gewaltverherrlichenden oder illegalen Inhalte.\nGekennzeichnete Werbung ist nur mit vorheriger Genehmigung erlaubt.', en:'Only upload photos and texts for which you own the copyright.\nNo pornographic, glorifying violence or illegal content.\nLabelled advertising is only permitted with prior approval.', fr:'Ne téléchargez que des photos et textes dont vous détenez les droits.\nPas de contenu pornographique, faisant l\'apologie de la violence ou illégal.\nLa publicité n\'est autorisée qu\'avec une approbation préalable.' },
  { key:'legal.guide_r6_title',  de:'Datenschutz anderer Nutzer', en:'Privacy of other users', fr:'Vie privée des autres utilisateurs' },
  { key:'legal.guide_r6_items',  de:'Veröffentliche keine persönlichen Daten anderer ohne Zustimmung.\nTeile keine Standortdaten, die andere gefährden könnten.\nScreenshots von Privatnachrichten dürfen nicht ohne Erlaubnis geteilt werden.', en:'Do not publish personal data of others without consent.\nDo not share location data that could endanger others.\nScreenshots of private messages may not be shared without permission.', fr:'Ne publiez pas de données personnelles d\'autrui sans consentement.\nNe partagez pas de données de localisation pouvant mettre les autres en danger.\nLes captures d\'écran de messages privés ne peuvent pas être partagées sans permission.' },
  { key:'legal.guide_r7_title',  de:'Spam & Werbung', en:'Spam & advertising', fr:'Spam & publicité' },
  { key:'legal.guide_r7_items',  de:'Kein Massen-Posting identischer oder irrelevanter Inhalte.\nKeine unverlangte Werbung in Fangberichten oder Kommentaren.\nAffiliate-Links sind nur mit deutlicher Kennzeichnung erlaubt.', en:'No mass posting of identical or irrelevant content.\nNo unsolicited advertising in catch reports or comments.\nAffiliate links are only permitted with clear labelling.', fr:'Pas de publication en masse de contenu identique ou non pertinent.\nPas de publicité non sollicitée dans les rapports ou commentaires.\nLes liens d\'affiliation ne sont autorisés qu\'avec une identification claire.' },
  { key:'legal.guide_r8_title',  de:'Meldungen & Konsequenzen', en:'Reports & consequences', fr:'Signalements & conséquences' },
  { key:'legal.guide_r8_items',  de:'Nutze die Meldefunktion für Regelverstöße – nicht für persönliche Konflikte.\nFalschmeldungen können zum Verlust des Meldeprivilegs führen.\nBei schwerwiegenden Verstößen behalten wir uns eine dauerhafte Sperrung vor.', en:'Use the report function for rule violations – not for personal conflicts.\nFalse reports can lead to loss of reporting privilege.\nFor serious violations we reserve the right to impose a permanent ban.', fr:'Utilisez la fonction de signalement pour les infractions – pas pour les conflits personnels.\nDes signalements abusifs peuvent entraîner la perte du privilège de signalement.\nPour les infractions graves, nous nous réservons le droit de procéder à un bannissement.' },
  { key:'legal.guide_r9_title',  de:'Änderungen der Regeln', en:'Changes to the rules', fr:'Modifications des règles' },
  { key:'legal.guide_r9_items',  de:'Wir behalten uns vor, diese Regeln jederzeit anzupassen.\nÄnderungen werden in der App kommuniziert.\nDie weitere Nutzung der App gilt als Zustimmung zu den aktualisierten Regeln.', en:'We reserve the right to amend these rules at any time.\nChanges will be communicated within the app.\nContinued use of the app constitutes acceptance of the updated rules.', fr:'Nous nous réservons le droit de modifier ces règles à tout moment.\nLes modifications seront communiquées dans l\'application.\nLa poursuite de l\'utilisation vaut acceptation des règles mises à jour.' },

  // ── legal — privacy ───────────────────────────────────────────────────────
  { key:'legal.privacy_title',    de:'Datenschutzerklärung', en:'Privacy Policy', fr:'Politique de confidentialité' },
  { key:'legal.privacy_intro',    de:'Der Schutz deiner persönlichen Daten ist uns wichtig. Nachfolgend informieren wir dich umfassend über die Erhebung, Verarbeitung und Nutzung deiner Daten.', en:'The protection of your personal data is important to us. Below we inform you comprehensively about the collection, processing and use of your data.', fr:'La protection de vos données personnelles est importante pour nous. Vous trouverez ci-dessous des informations complètes sur la collecte, le traitement et l\'utilisation de vos données.' },
  { key:'legal.privacy_s1_title', de:'1. Verantwortlicher', en:'1. Controller', fr:'1. Responsable du traitement' },
  { key:'legal.privacy_s1_contact_note', de:'Bei Fragen zum Datenschutz wende dich bitte per E-Mail an uns.', en:'For questions about data protection please contact us by email.', fr:'Pour toute question relative à la protection des données, veuillez nous contacter par e-mail.' },
  { key:'legal.privacy_s2_title', de:'2. Grundsätze der Datenverarbeitung', en:'2. Principles of data processing', fr:'2. Principes du traitement des données' },
  { key:'legal.privacy_s2_body',  de:'Wir verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung der App-Funktionen notwendig ist oder du eingewilligt hast.\nRechtsgrundlagen: Art. 6 Abs. 1 lit. b DSGVO (Vertragserfüllung), Art. 6 Abs. 1 lit. f DSGVO (berechtigte Interessen).\nDeine Daten werden nicht zu Werbezwecken an Dritte verkauft.', en:'We only process personal data to the extent necessary to provide the app functions or if you have consented.\nLegal bases: Art. 6(1)(b) GDPR (performance of contract), Art. 6(1)(f) GDPR (legitimate interests).\nYour data is not sold to third parties for advertising purposes.', fr:'Nous ne traitons les données personnelles que dans la mesure nécessaire à la fourniture des fonctions de l\'application.\nBases légales : art. 6, par. 1, lit. b RGPD, art. 6, par. 1, lit. f RGPD.\nVos données ne sont pas vendues à des tiers à des fins publicitaires.' },
  { key:'legal.privacy_s3_title',   de:'3. Verarbeitete Daten', en:'3. Data processed', fr:'3. Données traitées' },
  { key:'legal.privacy_s3_1_title', de:'3.1 Registrierung & Profil', en:'3.1 Registration & profile', fr:'3.1 Inscription & profil' },
  { key:'legal.privacy_s3_1_body',  de:'Bei der Registrierung erheben wir: Name, E-Mail-Adresse, Passwort (verschlüsselt), Heimatregion, Erfahrungsstufe und Sprachpräferenz.\nDiese Daten werden zur Accountverwaltung und Personalisierung der App genutzt.', en:'During registration we collect: name, email address, password (encrypted), home region, skill level and language preference.\nThis data is used for account management and personalisation of the app.', fr:'Lors de l\'inscription, nous collectons : nom, adresse e-mail, mot de passe (chiffré), région d\'origine, niveau d\'expérience et préférence linguistique.' },
  { key:'legal.privacy_s3_2_title', de:'3.2 Fangbuch', en:'3.2 Catch log', fr:'3.2 Journal de pêche' },
  { key:'legal.privacy_s3_2_body',  de:'Eingetragene Fänge enthalten: Fischart, Gewicht, Länge, Gewässer, Datum/Uhrzeit, Köder, Technik, optionale Notizen und optionale Fotos.\nNur du und ggf. andere Nutzer entsprechend deiner Sichtbarkeitseinstellung können deine Fänge sehen.', en:'Logged catches contain: fish species, weight, length, water body, date/time, bait, technique, optional notes and optional photos.\nOnly you and any other users according to your visibility setting can see your catches.', fr:'Les prises enregistrées contiennent : espèce, poids, longueur, plan d\'eau, date/heure, appât, technique, notes et photos facultatives.' },
  { key:'legal.privacy_s3_3_title', de:'3.3 Angelspots', en:'3.3 Fishing spots', fr:'3.3 Spots de pêche' },
  { key:'legal.privacy_s3_3_body',  de:'Gespeicherte Spots enthalten: Name, Beschreibung, GPS-Koordinaten und Zielarten.\nDie Sichtbarkeit (privat/Freunde/öffentlich) bestimmst du selbst.', en:'Saved spots contain: name, description, GPS coordinates and target species.\nYou determine the visibility (private/friends/public) yourself.', fr:'Les spots enregistrés contiennent : nom, description, coordonnées GPS et espèces cibles.\nVous déterminez vous-même la visibilité.' },
  { key:'legal.privacy_s3_4_title', de:'3.4 KI-Bissindex', en:'3.4 AI bite index', fr:'3.4 Indice de morsure IA' },
  { key:'legal.privacy_s3_4_body',  de:'Wenn du den Bissindex verwendest, wird dein Standort sowie aktuelle Wetterdaten an die Google Gemini AI weitergeleitet.\nDie Anfrage erfolgt serverseitig – deine IP-Adresse wird dabei nicht direkt an Google übermittelt.', en:'When you use the bite index, your location and current weather data are forwarded to Google Gemini AI.\nThe request is made server-side – your IP address is not transmitted directly to Google.', fr:'Lorsque vous utilisez l\'indice de morsure, votre position et les données météo sont transmises à Google Gemini AI.\nLa requête est effectuée côté serveur.' },
  { key:'legal.privacy_s3_5_title', de:'3.5 Community-Inhalte', en:'3.5 Community content', fr:'3.5 Contenu communautaire' },
  { key:'legal.privacy_s3_5_body',  de:'Als „öffentlich" markierte Fänge und Spots sind für alle Nutzer sichtbar.\nKommentare und Reaktionen auf Beiträge werden gespeichert und sind für die jeweilige Zielgruppe sichtbar.', en:'Catches and spots marked as "public" are visible to all users.\nComments and reactions to posts are saved and visible to the respective target audience.', fr:'Les prises et spots marqués comme "publics" sont visibles par tous les utilisateurs.\nLes commentaires et réactions sont enregistrés.' },
  { key:'legal.privacy_s3_6_title', de:'3.6 Meldungen', en:'3.6 Reports', fr:'3.6 Signalements' },
  { key:'legal.privacy_s3_6_body',  de:'Wenn du einen Nutzer meldest, werden der Bericht und dein Nutzerprofil für die Moderation gespeichert.\nDaten aus Meldungen werden nur zur Bearbeitung durch Administratoren verwendet.', en:'When you report a user, the report and your user profile are saved for moderation.\nData from reports is only used for processing by administrators.', fr:'Lorsque vous signalez un utilisateur, le signalement et votre profil sont enregistrés pour la modération.' },
  { key:'legal.privacy_s3_7_title', de:'3.7 Passwort-Reset', en:'3.7 Password reset', fr:'3.7 Réinitialisation du mot de passe' },
  { key:'legal.privacy_s3_7_body',  de:'Für den Passwort-Reset speichern wir temporär ein verschlüsseltes Token mit Ablaufzeit (15 Minuten).\nNach dem Reset wird das Token gelöscht.', en:'For password reset we temporarily store an encrypted token with an expiry time (15 minutes).\nThe token is deleted after the reset.', fr:'Pour la réinitialisation, nous stockons temporairement un jeton chiffré avec un délai d\'expiration (15 minutes).' },
  { key:'legal.privacy_s4_title',   de:'4. Speicherung & Löschung', en:'4. Storage & deletion', fr:'4. Stockage & suppression' },
  { key:'legal.privacy_s4_body',    de:'Deine Daten werden auf Servern in der EU gespeichert.\nNach Kontolöschung werden alle persönlichen Daten innerhalb von 30 Tagen gelöscht.\nBackups werden nach 30 Tagen überschrieben.', en:'Your data is stored on servers in the EU.\nAfter account deletion, all personal data will be deleted within 30 days.\nBackups are overwritten after 30 days.', fr:'Vos données sont stockées sur des serveurs dans l\'UE.\nAprès la suppression du compte, toutes les données personnelles seront supprimées dans les 30 jours.' },
  { key:'legal.privacy_s5_title',   de:'5. Drittanbieter & Auftragsverarbeiter', en:'5. Third parties & processors', fr:'5. Tiers & sous-traitants' },
  { key:'legal.privacy_s5_intro',   de:'Folgende externe Dienste werden genutzt:', en:'The following external services are used:', fr:'Les services externes suivants sont utilisés :' },
  { key:'legal.privacy_s5_th_service',  de:'Dienst',              en:'Service',           fr:'Service' },
  { key:'legal.privacy_s5_th_purpose',  de:'Zweck',               en:'Purpose',           fr:'Objet' },
  { key:'legal.privacy_s5_th_data',     de:'Übermittelte Daten',  en:'Data transmitted',  fr:'Données transmises' },
  { key:'legal.privacy_s5_th_location', de:'Standort',            en:'Location',          fr:'Lieu' },
  { key:'legal.privacy_s5_th_privacy',  de:'Datenschutz',         en:'Privacy policy',    fr:'Politique de confidentialité' },
  { key:'legal.privacy_s5_r1_purpose',  de:'KI-Bissindex / Angelprognose', en:'AI bite index / fishing forecast', fr:'Indice de morsure IA / prévision de pêche' },
  { key:'legal.privacy_s5_r1_data',     de:'Koordinaten, Wetterdaten, Spracheinstellung', en:'Coordinates, weather data, language setting', fr:'Coordonnées, données météo, paramètre de langue' },
  { key:'legal.privacy_s5_r2_purpose',  de:'Wetterdaten für Bissindex', en:'Weather data for bite index', fr:'Données météo pour l\'indice de morsure' },
  { key:'legal.privacy_s5_r2_data',     de:'Koordinaten',         en:'Coordinates',       fr:'Coordonnées' },
  { key:'legal.privacy_s5_r2_location', de:'EU (Schweiz)',         en:'EU (Switzerland)',  fr:'UE (Suisse)' },
  { key:'legal.privacy_s5_r3_purpose',  de:'Geocoding (Ortsname → Koordinaten)', en:'Geocoding (place name → coordinates)', fr:'Géocodage (nom de lieu → coordonnées)' },
  { key:'legal.privacy_s5_r3_data',     de:'Suchbegriff (Ortsname)', en:'Search term (place name)', fr:'Terme de recherche (nom de lieu)' },
  { key:'legal.privacy_s5_r4_purpose',  de:'Hintergrundbilder',   en:'Background images', fr:'Images d\'arrière-plan' },
  { key:'legal.privacy_s5_r4_data',     de:'IP-Adresse (CDN-Anfrage)', en:'IP address (CDN request)', fr:'Adresse IP (requête CDN)' },
  { key:'legal.privacy_s5_r5_purpose',  de:'Kartenansicht für Spots', en:'Map view for spots', fr:'Vue carte pour les spots' },
  { key:'legal.privacy_s5_r5_data',     de:'IP-Adresse, Kartensegment', en:'IP address, map segment', fr:'Adresse IP, segment de carte' },
  { key:'legal.privacy_s5_r6_purpose',  de:'Versand von Passwort-Reset-E-Mails', en:'Sending password reset emails', fr:'Envoi d\'e-mails de réinitialisation' },
  { key:'legal.privacy_s5_r6_data',     de:'Empfänger-E-Mail, Name, Reset-Link', en:'Recipient email, name, reset link', fr:'E-mail du destinataire, nom, lien de réinitialisation' },
  { key:'legal.privacy_s5_r6_location', de:'Deutschland (EU)',    en:'Germany (EU)',      fr:'Allemagne (UE)' },
  { key:'legal.privacy_s5_footer',      de:'Alle genannten Drittanbieter sind vertraglich zur DSGVO-konformen Verarbeitung verpflichtet.\nBei Drittanbietern außerhalb der EU sind Standardvertragsklauseln (SCC) vereinbart.', en:'All named third-party providers are contractually obligated to process data in compliance with GDPR.\nFor third-party providers outside the EU, standard contractual clauses (SCC) are agreed.', fr:'Tous les fournisseurs tiers nommés sont contractuellement tenus de traiter les données conformément au RGPD.\nPour les fournisseurs hors UE, des clauses contractuelles standard (SCC) sont convenues.' },
  { key:'legal.privacy_s6_title',       de:'6. Cookies & lokale Speicherung', en:'6. Cookies & local storage', fr:'6. Cookies & stockage local' },
  { key:'legal.privacy_s6_intro',       de:'Wir verwenden nur technisch notwendige Speicher-Mechanismen:', en:'We only use technically necessary storage mechanisms:', fr:'Nous n\'utilisons que des mécanismes de stockage techniquement nécessaires :' },
  { key:'legal.privacy_s6_th_name',     de:'Name',                en:'Name',              fr:'Nom' },
  { key:'legal.privacy_s6_th_type',     de:'Typ',                 en:'Type',              fr:'Type' },
  { key:'legal.privacy_s6_th_purpose',  de:'Zweck',               en:'Purpose',           fr:'Objet' },
  { key:'legal.privacy_s6_th_duration', de:'Dauer',               en:'Duration',          fr:'Durée' },
  { key:'legal.privacy_s6_th_category', de:'Kategorie',           en:'Category',          fr:'Catégorie' },
  { key:'legal.privacy_s6_token_purpose',  de:'Authentifizierung (JWT)', en:'Authentication (JWT)', fr:'Authentification (JWT)' },
  { key:'legal.privacy_s6_token_duration', de:'30 Tage',          en:'30 days',           fr:'30 jours' },
  { key:'legal.privacy_s6_token_category',de:'Notwendig',         en:'Necessary',         fr:'Nécessaire' },
  { key:'legal.privacy_s6_footer',      de:'Es werden keine Tracking-Cookies, Analyse-Cookies oder Marketing-Cookies gesetzt.\nEin Cookie-Banner ist daher nicht erforderlich.', en:'No tracking cookies, analytics cookies or marketing cookies are set.\nA cookie banner is therefore not required.', fr:'Aucun cookie de suivi, d\'analyse ou de marketing n\'est défini.\nUne bannière de cookies n\'est donc pas nécessaire.' },
  { key:'legal.privacy_s7_title',       de:'7. Standortdaten', en:'7. Location data', fr:'7. Données de localisation' },
  { key:'legal.privacy_s7_intro',       de:'Standortdaten werden nur genutzt wenn du aktiv zustimmst:', en:'Location data is only used when you actively consent:', fr:'Les données de localisation ne sont utilisées que lorsque vous consentez activement :' },
  { key:'legal.privacy_s7_bullets',     de:'Bissindex: Nur wenn du auf „Meinen Standort verwenden" klickst\nSpots: Nur wenn du auf „GPS-Position verwenden" klickst\nDaten werden nicht im Hintergrund erfasst\nKoordinaten werden nicht dauerhaft gespeichert', en:'Bite index: Only when you click "Use my location"\nSpots: Only when you click "Use GPS position"\nData is not recorded in the background\nCoordinates are not permanently stored', fr:'Indice de morsure : Uniquement lorsque vous cliquez sur "Utiliser ma position"\nSpots : Uniquement lorsque vous cliquez sur "Utiliser la position GPS"\nLes données ne sont pas enregistrées en arrière-plan\nLes coordonnées ne sont pas stockées de façon permanente' },
  { key:'legal.privacy_s7_footer',      de:'Browser-API: Die Standortabfrage erfolgt über die Browser-Geolocation-API. Du wirst dabei vom Browser um Erlaubnis gefragt.', en:'Browser API: The location query is made via the browser Geolocation API. Your browser will ask for permission.', fr:'API de navigateur : La requête de localisation est effectuée via l\'API de géolocalisation du navigateur.' },
  { key:'legal.privacy_s8_title',       de:'8. Deine Rechte', en:'8. Your rights', fr:'8. Vos droits' },
  { key:'legal.privacy_s8_intro',       de:'Als betroffene Person hast du folgende Rechte gemäß DSGVO:', en:'As a data subject you have the following rights under the GDPR:', fr:'En tant que personne concernée, vous disposez des droits suivants au titre du RGPD :' },
  { key:'legal.privacy_s8_contact',     de:'Zur Ausübung deiner Rechte kontaktiere uns per E-Mail:', en:'To exercise your rights please contact us by email:', fr:'Pour exercer vos droits, veuillez nous contacter par e-mail :' },
  { key:'legal.privacy_right1_title',   de:'Auskunft',          en:'Access',          fr:'Accès' },
  { key:'legal.privacy_right1_desc',    de:'Recht auf Information, welche Daten wir über dich verarbeiten (Art. 15 DSGVO)', en:'Right to information about which data we process about you (Art. 15 GDPR)', fr:'Droit à l\'information sur les données que nous traitons vous concernant (art. 15 RGPD)' },
  { key:'legal.privacy_right2_title',   de:'Berichtigung',      en:'Rectification',   fr:'Rectification' },
  { key:'legal.privacy_right2_desc',    de:'Recht auf Korrektur falscher oder unvollständiger Daten (Art. 16 DSGVO)', en:'Right to correction of incorrect or incomplete data (Art. 16 GDPR)', fr:'Droit à la correction des données inexactes ou incomplètes (art. 16 RGPD)' },
  { key:'legal.privacy_right3_title',   de:'Löschung',          en:'Erasure',         fr:'Effacement' },
  { key:'legal.privacy_right3_desc',    de:'Recht auf Löschung deiner Daten (Art. 17 DSGVO)', en:'Right to erasure of your data (Art. 17 GDPR)', fr:'Droit à la suppression de vos données (art. 17 RGPD)' },
  { key:'legal.privacy_right4_title',   de:'Einschränkung',     en:'Restriction',     fr:'Limitation' },
  { key:'legal.privacy_right4_desc',    de:'Recht auf Einschränkung der Verarbeitung (Art. 18 DSGVO)', en:'Right to restriction of processing (Art. 18 GDPR)', fr:'Droit à la limitation du traitement (art. 18 RGPD)' },
  { key:'legal.privacy_right5_title',   de:'Datenübertragbarkeit', en:'Portability',  fr:'Portabilité' },
  { key:'legal.privacy_right5_desc',    de:'Recht auf Erhalt deiner Daten in maschinenlesbarem Format (Art. 20 DSGVO)', en:'Right to receive your data in machine-readable format (Art. 20 GDPR)', fr:'Droit de recevoir vos données dans un format lisible par machine (art. 20 RGPD)' },
  { key:'legal.privacy_right6_title',   de:'Widerspruch',       en:'Objection',       fr:'Opposition' },
  { key:'legal.privacy_right6_desc',    de:'Recht auf Widerspruch gegen die Verarbeitung (Art. 21 DSGVO)', en:'Right to object to processing (Art. 21 GDPR)', fr:'Droit de s\'opposer au traitement (art. 21 RGPD)' },
  { key:'legal.privacy_right7_title',   de:'Widerruf',          en:'Withdrawal',      fr:'Retrait' },
  { key:'legal.privacy_right7_desc',    de:'Recht auf Widerruf erteilter Einwilligungen (Art. 7 Abs. 3 DSGVO)', en:'Right to withdraw consents given (Art. 7(3) GDPR)', fr:'Droit de retirer les consentements accordés (art. 7, par. 3, RGPD)' },
  { key:'legal.privacy_right8_title',   de:'Beschwerde',        en:'Complaint',       fr:'Plainte' },
  { key:'legal.privacy_right8_desc',    de:'Recht auf Beschwerde bei einer Aufsichtsbehörde (Art. 77 DSGVO)', en:'Right to lodge a complaint with a supervisory authority (Art. 77 GDPR)', fr:'Droit de déposer une plainte auprès d\'une autorité de contrôle (art. 77 RGPD)' },
  { key:'legal.privacy_s9_title',       de:'9. Minderjährige', en:'9. Minors', fr:'9. Mineurs' },
  { key:'legal.privacy_s9_body',        de:'AngelMate richtet sich an Nutzer ab 16 Jahren.\nPersonen unter 16 Jahren dürfen die App nur mit Zustimmung eines Erziehungsberechtigten nutzen.\nFalls wir erfahren, dass wir Daten von Minderjährigen unter 16 Jahren verarbeitet haben, werden diese unverzüglich gelöscht.', en:'AngelMate is aimed at users aged 16 and over.\nPersons under 16 may only use the app with the consent of a parent or guardian.\nIf we become aware that we have processed data from minors under 16, this will be deleted immediately.', fr:'AngelMate s\'adresse aux utilisateurs de 16 ans et plus.\nLes personnes de moins de 16 ans ne peuvent utiliser l\'application qu\'avec le consentement d\'un parent ou tuteur.' },
  { key:'legal.privacy_s10_title',      de:'10. Änderungen dieser Datenschutzerklärung', en:'10. Changes to this privacy policy', fr:'10. Modifications de la présente politique de confidentialité' },
  { key:'legal.privacy_s10_body',       de:'Wir behalten uns vor, diese Datenschutzerklärung bei Bedarf zu aktualisieren.\nDie aktuelle Version ist stets in der App abrufbar.\nBei wesentlichen Änderungen informieren wir dich per E-Mail oder In-App-Hinweis.', en:'We reserve the right to update this privacy policy as necessary.\nThe current version is always available in the app.\nFor significant changes, we will inform you by email or in-app notice.', fr:'Nous nous réservons le droit de mettre à jour la présente politique de confidentialité si nécessaire.\nLa version actuelle est toujours disponible dans l\'application.' },
  { key:'legal.privacy_date',           de:'Stand: April 2026', en:'Last updated: April 2026', fr:'Dernière mise à jour : avril 2026' },

  // ── license ───────────────────────────────────────────────────────────────
  { key:'license.title',       de:'Angelschein',             en:'Fishing Licence',          fr:'Permis de pêche' },
  { key:'license.subtitle',    de:'Alles, was du über den Angelschein wissen musst.', en:'Everything you need to know about your fishing licence.', fr:'Tout ce que vous devez savoir sur votre permis de pêche.' },
  { key:'license.hero_title',  de:'Dein Weg zum Angelschein', en:'Your path to a fishing licence', fr:'Votre chemin vers le permis de pêche' },
  { key:'license.hero_body',   de:'In Deutschland brauchst du einen <strong>staatlichen Fischereischein</strong> sowie einen Erlaubnisschein des Gewässerbewirtschafters. fishing-king.de bietet dir eine einfache Online-Vorbereitung für die Fischereiprüfung.', en:'In Germany you need a <strong>state fishing licence</strong> and a permit from the water authority. fishing-king.de offers easy online preparation for the fishing exam.', fr:'En Allemagne, vous avez besoin d\'un <strong>permis de pêche d\'État</strong> et d\'une autorisation du gestionnaire des eaux. fishing-king.de propose une préparation en ligne facile à l\'examen de pêche.' },
  { key:'license.cta_btn',     de:'Zu fishing-king.de',      en:'Go to fishing-king.de',    fr:'Aller sur fishing-king.de' },
  { key:'license.steps_title', de:'In 4 Schritten zum Angelschein', en:'4 steps to your fishing licence', fr:'4 étapes pour obtenir votre permis de pêche' },
  { key:'license.step1_title', de:'Online lernen',           en:'Learn online',             fr:'Apprendre en ligne' },
  { key:'license.step1_text',  de:'Bereite dich mit Online-Kursen, Lernkarten und Prüfungssimulationen auf die Fischereiprüfung vor.', en:'Prepare for the fishing exam with online courses, flashcards and practice tests.', fr:'Préparez-vous à l\'examen avec des cours en ligne, des fiches et des simulations d\'examen.' },
  { key:'license.step2_title', de:'Prüfung ablegen',         en:'Take the exam',            fr:'Passer l\'examen' },
  { key:'license.step2_text',  de:'Die staatliche Fischereiprüfung findet beim zuständigen Amt statt und besteht aus einem schriftlichen Teil.', en:'The state fishing exam takes place at the relevant authority and consists of a written part.', fr:'L\'examen de pêche d\'État a lieu auprès de l\'autorité compétente et comprend une partie écrite.' },
  { key:'license.step3_title', de:'Fischereischein beantragen', en:'Apply for the licence', fr:'Demander le permis' },
  { key:'license.step3_text',  de:'Nach bestandener Prüfung beantragst du beim Landratsamt deinen staatlichen Fischereischein.', en:'After passing the exam, you apply for your state fishing licence at the district office.', fr:'Après avoir réussi l\'examen, vous demandez votre permis de pêche d\'État auprès de la sous-préfecture.' },
  { key:'license.step4_title', de:'Erlaubnisschein kaufen',  en:'Buy a permit',             fr:'Acheter une autorisation' },
  { key:'license.step4_text',  de:'Für jedes Gewässer brauchst du zusätzlich einen Erlaubnisschein des Bewirtschafters – oft günstig beim Angelverein erhältlich.', en:'For each water you also need a permit from the operator – often available cheaply from the fishing club.', fr:'Pour chaque plan d\'eau, vous avez besoin d\'une autorisation du gestionnaire – souvent disponible à faible coût auprès du club de pêche.' },
  { key:'license.faq_title',   de:'Häufige Fragen',          en:'Frequently asked questions', fr:'Questions fréquentes' },
  { key:'license.faq1_title',  de:'Wer braucht einen Angelschein?', en:'Who needs a fishing licence?', fr:'Qui a besoin d\'un permis de pêche ?' },
  { key:'license.faq1_text',   de:'In Deutschland benötigt jeder, der in öffentlichen Gewässern angeln möchte, einen gültigen staatlichen Fischereischein.', en:'In Germany, anyone who wants to fish in public waters needs a valid state fishing licence.', fr:'En Allemagne, toute personne souhaitant pêcher dans des eaux publiques a besoin d\'un permis de pêche d\'État valide.' },
  { key:'license.faq2_title',  de:'Gilt der Schein in ganz Deutschland?', en:'Is the licence valid throughout Germany?', fr:'Le permis est-il valable dans toute l\'Allemagne ?' },
  { key:'license.faq2_text',   de:'Der staatliche Fischereischein ist bundesweit gültig, aber jedes Bundesland hat eigene Regelungen für die Prüfung.', en:'The state fishing licence is valid throughout Germany, but each federal state has its own exam regulations.', fr:'Le permis de pêche d\'État est valable dans toute l\'Allemagne, mais chaque Land a ses propres réglementations.' },
  { key:'license.faq3_title',  de:'Wie lange ist die Vorbereitung?', en:'How long is the preparation?', fr:'Combien de temps dure la préparation ?' },
  { key:'license.faq3_text',   de:'Mit intensivem Lernen kann man sich in 2–4 Wochen auf die Prüfung vorbereiten.', en:'With intensive study, you can prepare for the exam in 2–4 weeks.', fr:'Avec un apprentissage intensif, vous pouvez vous préparer à l\'examen en 2 à 4 semaines.' },
  { key:'license.faq4_title',  de:'Was kostet der Angelschein?', en:'How much does the fishing licence cost?', fr:'Combien coûte le permis de pêche ?' },
  { key:'license.faq4_text',   de:'Die Prüfungsgebühr liegt meist zwischen 20–50 €, der Fischereischein selbst kostet weitere 10–30 €.', en:'The exam fee is usually between €20–50, and the fishing licence itself costs a further €10–30.', fr:'Les frais d\'examen se situent généralement entre 20 et 50 €, et le permis de pêche lui-même coûte 10 à 30 € supplémentaires.' },
  { key:'license.bottom_cta',  de:'Bereit, deinen Angelschein zu machen?', en:'Ready to get your fishing licence?', fr:'Prêt à obtenir votre permis de pêche ?' },
  { key:'license.start_btn',   de:'Jetzt starten',           en:'Start now',                fr:'Commencer maintenant' },
  { key:'license.hint',        de:'Schnell, einfach und komplett online.', en:'Fast, easy and completely online.', fr:'Rapide, simple et entièrement en ligne.' },
];

async function main() {
  const passwordHash = await import('bcryptjs').then(m => m.default.hash('password123', 12));

  await prisma.user.upsert({
    where: { email: 'max@example.com' },
    update: {},
    create: {
      name: 'Max Angler',
      email: 'max@example.com',
      passwordHash,
      homeRegion: 'Berlin/Brandenburg',
      skillLevel: 'intermediate',
    },
  });

  const rows = KEYS.flatMap((k) =>
    ['de', 'en', 'fr'].map((l) => ({ locale: l, key: k.key, value: k[l] }))
  );
  const result = await prisma.translation.createMany({ data: rows, skipDuplicates: true });
  console.log(`Seeded ${result.count} translation rows (${KEYS.length} keys × 3 locales).`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
