-- AlterEnum
ALTER TYPE "AdPosition" ADD VALUE 'CATCHES_TOP';
ALTER TYPE "AdPosition" ADD VALUE 'CATCHES_BOTTOM';
ALTER TYPE "AdPosition" ADD VALUE 'SPOTS_TOP';
ALTER TYPE "AdPosition" ADD VALUE 'BITES_TOP';
